
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_imageio_IIOException__
#define __javax_imageio_IIOException__

#pragma interface

#include <java/io/IOException.h>
extern "Java"
{
  namespace javax
  {
    namespace imageio
    {
        class IIOException;
    }
  }
}

class javax::imageio::IIOException : public ::java::io::IOException
{

public:
  IIOException(::java::lang::String *);
  IIOException(::java::lang::String *, ::java::lang::Throwable *);
  static ::java::lang::Class class$;
};

#endif // __javax_imageio_IIOException__
