extern "C" void _M2_RTExceptions_init(int argc, char *argv[]);
extern "C" void _M2_RTExceptions_finish(int argc, char *argv[]);
extern "C" void _M2_M2EXCEPTION_init(int argc, char *argv[]);
extern "C" void _M2_M2EXCEPTION_finish(int argc, char *argv[]);
extern "C" void _M2_M2RTS_init(int argc, char *argv[]);
extern "C" void _M2_M2RTS_finish(int argc, char *argv[]);
extern "C" void _M2_SysExceptions_init(int argc, char *argv[]);
extern "C" void _M2_SysExceptions_finish(int argc, char *argv[]);
extern "C" void _M2_StrLib_init(int argc, char *argv[]);
extern "C" void _M2_StrLib_finish(int argc, char *argv[]);
extern "C" void _M2_errno_init(int argc, char *argv[]);
extern "C" void _M2_errno_finish(int argc, char *argv[]);
extern "C" void _M2_termios_init(int argc, char *argv[]);
extern "C" void _M2_termios_finish(int argc, char *argv[]);
extern "C" void _M2_IO_init(int argc, char *argv[]);
extern "C" void _M2_IO_finish(int argc, char *argv[]);
extern "C" void _M2_StdIO_init(int argc, char *argv[]);
extern "C" void _M2_StdIO_finish(int argc, char *argv[]);
extern "C" void _M2_Debug_init(int argc, char *argv[]);
extern "C" void _M2_Debug_finish(int argc, char *argv[]);
extern "C" void _M2_SysStorage_init(int argc, char *argv[]);
extern "C" void _M2_SysStorage_finish(int argc, char *argv[]);
extern "C" void _M2_Storage_init(int argc, char *argv[]);
extern "C" void _M2_Storage_finish(int argc, char *argv[]);
extern "C" void _M2_StrIO_init(int argc, char *argv[]);
extern "C" void _M2_StrIO_finish(int argc, char *argv[]);
extern "C" void _M2_DynamicStrings_init(int argc, char *argv[]);
extern "C" void _M2_DynamicStrings_finish(int argc, char *argv[]);
extern "C" void _M2_Assertion_init(int argc, char *argv[]);
extern "C" void _M2_Assertion_finish(int argc, char *argv[]);
extern "C" void _M2_Indexing_init(int argc, char *argv[]);
extern "C" void _M2_Indexing_finish(int argc, char *argv[]);
extern "C" void _M2_NameKey_init(int argc, char *argv[]);
extern "C" void _M2_NameKey_finish(int argc, char *argv[]);
extern "C" void _M2_NumberIO_init(int argc, char *argv[]);
extern "C" void _M2_NumberIO_finish(int argc, char *argv[]);
extern "C" void _M2_PushBackInput_init(int argc, char *argv[]);
extern "C" void _M2_PushBackInput_finish(int argc, char *argv[]);
extern "C" void _M2_SymbolKey_init(int argc, char *argv[]);
extern "C" void _M2_SymbolKey_finish(int argc, char *argv[]);
extern "C" void _M2_UnixArgs_init(int argc, char *argv[]);
extern "C" void _M2_UnixArgs_finish(int argc, char *argv[]);
extern "C" void _M2_FIO_init(int argc, char *argv[]);
extern "C" void _M2_FIO_finish(int argc, char *argv[]);
extern "C" void _M2_SFIO_init(int argc, char *argv[]);
extern "C" void _M2_SFIO_finish(int argc, char *argv[]);
extern "C" void _M2_StrCase_init(int argc, char *argv[]);
extern "C" void _M2_StrCase_finish(int argc, char *argv[]);
extern "C" void _M2_bnflex_init(int argc, char *argv[]);
extern "C" void _M2_bnflex_finish(int argc, char *argv[]);
extern "C" void _M2_Lists_init(int argc, char *argv[]);
extern "C" void _M2_Lists_finish(int argc, char *argv[]);
extern "C" void _M2_Args_init(int argc, char *argv[]);
extern "C" void _M2_Args_finish(int argc, char *argv[]);
extern "C" void _M2_Output_init(int argc, char *argv[]);
extern "C" void _M2_Output_finish(int argc, char *argv[]);
extern "C" void _M2_pge_init(int argc, char *argv[]);
extern "C" void _M2_pge_finish(int argc, char *argv[]);
extern "C" void _exit(int);


int main(int argc, char *argv[])
{
   _M2_RTExceptions_init(argc, argv);
   _M2_M2EXCEPTION_init(argc, argv);
   _M2_M2RTS_init(argc, argv);
   _M2_SysExceptions_init(argc, argv);
   _M2_StrLib_init(argc, argv);
   _M2_errno_init(argc, argv);
   _M2_termios_init(argc, argv);
   _M2_IO_init(argc, argv);
   _M2_StdIO_init(argc, argv);
   _M2_Debug_init(argc, argv);
   _M2_SysStorage_init(argc, argv);
   _M2_Storage_init(argc, argv);
   _M2_StrIO_init(argc, argv);
   _M2_DynamicStrings_init(argc, argv);
   _M2_Assertion_init(argc, argv);
   _M2_Indexing_init(argc, argv);
   _M2_NameKey_init(argc, argv);
   _M2_NumberIO_init(argc, argv);
   _M2_PushBackInput_init(argc, argv);
   _M2_SymbolKey_init(argc, argv);
   _M2_UnixArgs_init(argc, argv);
   _M2_FIO_init(argc, argv);
   _M2_SFIO_init(argc, argv);
   _M2_StrCase_init(argc, argv);
   _M2_bnflex_init(argc, argv);
   _M2_Lists_init(argc, argv);
   _M2_Args_init(argc, argv);
   _M2_Output_init(argc, argv);
   _M2_pge_init(argc, argv);
   _M2_pge_finish(argc, argv);
   _M2_Output_finish(argc, argv);
   _M2_Args_finish(argc, argv);
   _M2_Lists_finish(argc, argv);
   _M2_bnflex_finish(argc, argv);
   _M2_StrCase_finish(argc, argv);
   _M2_SFIO_finish(argc, argv);
   _M2_FIO_finish(argc, argv);
   _M2_UnixArgs_finish(argc, argv);
   _M2_SymbolKey_finish(argc, argv);
   _M2_PushBackInput_finish(argc, argv);
   _M2_NumberIO_finish(argc, argv);
   _M2_NameKey_finish(argc, argv);
   _M2_Indexing_finish(argc, argv);
   _M2_Assertion_finish(argc, argv);
   _M2_DynamicStrings_finish(argc, argv);
   _M2_StrIO_finish(argc, argv);
   _M2_Storage_finish(argc, argv);
   _M2_SysStorage_finish(argc, argv);
   _M2_Debug_finish(argc, argv);
   _M2_StdIO_finish(argc, argv);
   _M2_IO_finish(argc, argv);
   _M2_termios_finish(argc, argv);
   _M2_errno_finish(argc, argv);
   _M2_StrLib_finish(argc, argv);
   _M2_SysExceptions_finish(argc, argv);
   _M2_M2RTS_finish(argc, argv);
   _M2_M2EXCEPTION_finish(argc, argv);
   _M2_RTExceptions_finish(argc, argv);
   return(0);
}
