
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_activation_DataHandlerDataSource__
#define __javax_activation_DataHandlerDataSource__

#pragma interface

#include <java/lang/Object.h>
extern "Java"
{
  namespace javax
  {
    namespace activation
    {
        class DataHandler;
        class DataHandlerDataSource;
    }
  }
}

class javax::activation::DataHandlerDataSource : public ::java::lang::Object
{

public: // actually package-private
  DataHandlerDataSource(::javax::activation::DataHandler *);
public:
  ::java::lang::String * getContentType();
  ::java::io::InputStream * getInputStream();
  ::java::lang::String * getName();
  ::java::io::OutputStream * getOutputStream();
public: // actually package-private
  ::javax::activation::DataHandler * __attribute__((aligned(__alignof__( ::java::lang::Object)))) dh;
public:
  static ::java::lang::Class class$;
};

#endif // __javax_activation_DataHandlerDataSource__
