
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_javax_net_ssl_provider_Handshake$buffer__
#define __gnu_javax_net_ssl_provider_Handshake$buffer__

#pragma interface

#include <java/lang/ThreadLocal.h>
extern "Java"
{
  namespace gnu
  {
    namespace javax
    {
      namespace net
      {
        namespace ssl
        {
          namespace provider
          {
              class Handshake$buffer;
          }
        }
      }
    }
  }
}

class gnu::javax::net::ssl::provider::Handshake$buffer : public ::java::lang::ThreadLocal
{

  Handshake$buffer();
public: // actually protected
  virtual ::java::lang::Object * initialValue();
public: // actually package-private
  virtual ::java::io::ByteArrayOutputStream * getBuffer();
  Handshake$buffer(::gnu::javax::net::ssl::provider::Handshake$buffer *);
  static const jint SIZE = 2048;
public:
  static ::java::lang::Class class$;
};

#endif // __gnu_javax_net_ssl_provider_Handshake$buffer__
