
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_lang_Double__
#define __java_lang_Double__

#pragma interface

#include <java/lang/Number.h>

class java::lang::Double : public ::java::lang::Number
{

public:
  Double(jdouble);
  Double(::java::lang::String *);
  static ::java::lang::String * toString(jdouble);
  static ::java::lang::String * toHexString(jdouble);
  static ::java::lang::Double * valueOf(jdouble);
  static ::java::lang::Double * valueOf(::java::lang::String *);
  static jdouble parseDouble(::java::lang::String *);
  static jboolean isNaN(jdouble);
  static jboolean isInfinite(jdouble);
  jboolean isNaN();
  jboolean isInfinite();
  ::java::lang::String * toString();
  jbyte byteValue();
  jshort shortValue();
  jint intValue();
  jlong longValue();
  jfloat floatValue();
  jdouble doubleValue();
  jint hashCode();
  jboolean equals(::java::lang::Object *);
  static jlong doubleToLongBits(jdouble);
  static jlong doubleToRawLongBits(jdouble);
  static jdouble longBitsToDouble(jlong);
  jint Double$compareTo(::java::lang::Double *);
  static jint compare(jdouble, jdouble);
  jint compareTo(::java::lang::Object *);
private:
  static const jlong serialVersionUID = -9172774392245257468LL;
public:
  static jdouble MAX_VALUE;
  static jdouble MIN_VALUE;
  static jdouble NEGATIVE_INFINITY;
  static jdouble POSITIVE_INFINITY;
  static jdouble NaN;
  static const jint SIZE = 64;
  static ::java::lang::Class * TYPE;
private:
  static ::java::lang::Double * ZERO;
  static ::java::lang::Double * ONE;
  jdouble __attribute__((aligned(__alignof__( ::java::lang::Number)))) value;
public:
  static ::java::lang::Class class$;
};

#endif // __java_lang_Double__
