
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_lang_Win32Process$EOFInputStream__
#define __java_lang_Win32Process$EOFInputStream__

#pragma interface

#include <java/io/InputStream.h>

class java::lang::Win32Process$EOFInputStream : public ::java::io::InputStream
{

  Win32Process$EOFInputStream();
public:
  virtual jint read();
public: // actually package-private
  static ::java::lang::Win32Process$EOFInputStream * instance;
public:
  static ::java::lang::Class class$;
};

#endif // __java_lang_Win32Process$EOFInputStream__
