
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __org_omg_CORBA_portable_IDLEntity__
#define __org_omg_CORBA_portable_IDLEntity__

#pragma interface

#include <java/lang/Object.h>
extern "Java"
{
  namespace org
  {
    namespace omg
    {
      namespace CORBA
      {
        namespace portable
        {
            class IDLEntity;
        }
      }
    }
  }
}

class org::omg::CORBA::portable::IDLEntity : public ::java::lang::Object
{

public:
  static ::java::lang::Class class$;
} __attribute__ ((java_interface));

#endif // __org_omg_CORBA_portable_IDLEntity__
