
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_util_concurrent_CopyOnWriteArrayList__
#define __java_util_concurrent_CopyOnWriteArrayList__

#pragma interface

#include <java/util/AbstractList.h>
#include <gcj/array.h>


class java::util::concurrent::CopyOnWriteArrayList : public ::java::util::AbstractList
{

public:
  CopyOnWriteArrayList();
  CopyOnWriteArrayList(::java::util::Collection *);
  CopyOnWriteArrayList(JArray< ::java::lang::Object * > *);
  virtual jint size();
  virtual jboolean isEmpty();
  virtual jboolean contains(::java::lang::Object *);
  virtual jint indexOf(::java::lang::Object *);
  virtual jint indexOf(::java::lang::Object *, jint);
  virtual jint lastIndexOf(::java::lang::Object *);
  virtual jint lastIndexOf(::java::lang::Object *, jint);
  virtual ::java::lang::Object * clone();
  virtual JArray< ::java::lang::Object * > * toArray();
  virtual JArray< ::java::lang::Object * > * toArray(JArray< ::java::lang::Object * > *);
  virtual ::java::lang::Object * get(jint);
  virtual ::java::lang::Object * set(jint, ::java::lang::Object *);
  virtual jboolean add(::java::lang::Object *);
  virtual void add(jint, ::java::lang::Object *);
  virtual ::java::lang::Object * remove(jint);
  virtual void clear();
  virtual jboolean addAll(::java::util::Collection *);
  virtual jboolean addAll(jint, ::java::util::Collection *);
  virtual jboolean addIfAbsent(::java::lang::Object *);
  virtual jint addAllAbsent(::java::util::Collection *);
private:
  void writeObject(::java::io::ObjectOutputStream *);
  void readObject(::java::io::ObjectInputStream *);
public: // actually package-private
  static jboolean equals(::java::lang::Object *, ::java::lang::Object *);
  virtual JArray< ::java::lang::Object * > * getArray();
private:
  JArray< ::java::lang::Object * > * __attribute__((aligned(__alignof__( ::java::util::AbstractList)))) data;
public:
  static ::java::lang::Class class$;
};

#endif // __java_util_concurrent_CopyOnWriteArrayList__
