
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_xml_parsers_ParserConfigurationException__
#define __javax_xml_parsers_ParserConfigurationException__

#pragma interface

#include <java/lang/Exception.h>
extern "Java"
{
  namespace javax
  {
    namespace xml
    {
      namespace parsers
      {
          class ParserConfigurationException;
      }
    }
  }
}

class javax::xml::parsers::ParserConfigurationException : public ::java::lang::Exception
{

public:
  ParserConfigurationException();
  ParserConfigurationException(::java::lang::String *);
  static ::java::lang::Class class$;
};

#endif // __javax_xml_parsers_ParserConfigurationException__
