
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_rmi_server_RMIFailureHandler__
#define __java_rmi_server_RMIFailureHandler__

#pragma interface

#include <java/lang/Object.h>
extern "Java"
{
  namespace java
  {
    namespace rmi
    {
      namespace server
      {
          class RMIFailureHandler;
      }
    }
  }
}

class java::rmi::server::RMIFailureHandler : public ::java::lang::Object
{

public:
  virtual jboolean failure(::java::lang::Exception *) = 0;
  static ::java::lang::Class class$;
} __attribute__ ((java_interface));

#endif // __java_rmi_server_RMIFailureHandler__
