
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_xml_dom_ls_DomLSOutput__
#define __gnu_xml_dom_ls_DomLSOutput__

#pragma interface

#include <java/lang/Object.h>
extern "Java"
{
  namespace gnu
  {
    namespace xml
    {
      namespace dom
      {
        namespace ls
        {
            class DomLSOutput;
        }
      }
    }
  }
}

class gnu::xml::dom::ls::DomLSOutput : public ::java::lang::Object
{

public:
  DomLSOutput();
  virtual ::java::io::Writer * getCharacterStream();
  virtual void setCharacterStream(::java::io::Writer *);
  virtual ::java::io::OutputStream * getByteStream();
  virtual void setByteStream(::java::io::OutputStream *);
  virtual ::java::lang::String * getSystemId();
  virtual void setSystemId(::java::lang::String *);
  virtual ::java::lang::String * getEncoding();
  virtual void setEncoding(::java::lang::String *);
private:
  ::java::io::OutputStream * __attribute__((aligned(__alignof__( ::java::lang::Object)))) out;
  ::java::lang::String * systemId;
  ::java::lang::String * encoding;
public:
  static ::java::lang::Class class$;
};

#endif // __gnu_xml_dom_ls_DomLSOutput__
