
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_java_awt_peer_qt_QtTextFieldPeer__
#define __gnu_java_awt_peer_qt_QtTextFieldPeer__

#pragma interface

#include <gnu/java/awt/peer/qt/QtComponentPeer.h>
extern "Java"
{
  namespace gnu
  {
    namespace java
    {
      namespace awt
      {
        namespace peer
        {
          namespace qt
          {
              class QtTextFieldPeer;
              class QtToolkit;
          }
        }
      }
    }
  }
  namespace java
  {
    namespace awt
    {
        class Dimension;
        class Rectangle;
        class TextField;
      namespace im
      {
          class InputMethodRequests;
      }
    }
  }
}

class gnu::java::awt::peer::qt::QtTextFieldPeer : public ::gnu::java::awt::peer::qt::QtComponentPeer
{

public:
  QtTextFieldPeer(::gnu::java::awt::peer::qt::QtToolkit *, ::java::awt::TextField *);
public: // actually protected
  virtual void init();
  virtual void setup();
private:
  void textChanged();
  jint getSelection(jboolean);
  ::java::awt::Dimension * getMinimumSizeNative(jint);
  ::java::awt::Dimension * getPreferredSizeNative(jint);
public:
  virtual jlong filterEvents(jlong);
  virtual jint getCaretPosition();
  virtual ::java::awt::Rectangle * getCharacterBounds(jint);
  virtual jint getIndexAtPoint(jint, jint);
  virtual ::java::awt::Dimension * getMinimumSize(jint);
  virtual ::java::awt::Dimension * getPreferredSize(jint);
  virtual jint getSelectionEnd();
  virtual jint getSelectionStart();
  virtual ::java::lang::String * getText();
  virtual ::java::awt::Dimension * minimumSize(jint);
  virtual ::java::awt::Dimension * preferredSize(jint);
  virtual void select(jint, jint);
  virtual void setCaretPosition(jint);
  virtual void setEchoCharacter(jchar);
  virtual void setEchoChar(jchar);
  virtual void setEditable(jboolean);
  virtual void setText(::java::lang::String *);
  virtual ::java::awt::im::InputMethodRequests * getInputMethodRequests();
  static ::java::lang::Class class$;
};

#endif // __gnu_java_awt_peer_qt_QtTextFieldPeer__
