
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_CORBA_NamingService_NameComponentComparator__
#define __gnu_CORBA_NamingService_NameComponentComparator__

#pragma interface

#include <java/lang/Object.h>
extern "Java"
{
  namespace gnu
  {
    namespace CORBA
    {
      namespace NamingService
      {
          class NameComponentComparator;
      }
    }
  }
}

class gnu::CORBA::NamingService::NameComponentComparator : public ::java::lang::Object
{

  NameComponentComparator();
public:
  jint compare(::java::lang::Object *, ::java::lang::Object *);
  jboolean equals(::java::lang::Object *);
  static ::gnu::CORBA::NamingService::NameComponentComparator * singleton;
  static ::java::lang::Class class$;
};

#endif // __gnu_CORBA_NamingService_NameComponentComparator__
