// generated by token_names.h.gen
tokens = {
	{ "identification", IDENTIFICATION }, // 258
	{ "identification division", IDENTIFICATION_DIV }, // 259
	{ "environment", ENVIRONMENT }, // 260
	{ "environment division", ENVIRONMENT_DIV }, // 261
	{ "data", DATA }, // 262
	{ "data division", DATA_DIV }, // 263
	{ "procedure", PROCEDURE }, // 264
	{ "procedure division", PROCEDURE_DIV }, // 265
	{ "file section", FILE_SECT }, // 266
	{ "input_output section", INPUT_OUTPUT_SECT }, // 267
	{ "linkage section", LINKAGE_SECT }, // 268
	{ "local_storage section", LOCAL_STORAGE_SECT }, // 269
	{ "working_storage section", WORKING_STORAGE_SECT }, // 270
	{ "object-computer", OBJECT_COMPUTER }, // 271
	{ "display-of", DISPLAY_OF }, // 272
	{ "end-function", END_FUNCTION }, // 273
	{ "end-program", END_PROGRAM }, // 274
	{ "end-subprogram", END_SUBPROGRAM }, // 275
	{ "justified", JUSTIFIED }, // 276
	{ "returning", RETURNING }, // 277
	{ "no-condition", NO_CONDITION }, // 278
	{ "alnum", ALNUM }, // 279
	{ "alphed", ALPHED }, // 280
	{ "error", ERROR }, // 281
	{ "exception", EXCEPTION }, // 282
	{ "size-error", SIZE_ERROR }, // 283
	{ "exception-name", EXCEPTION_NAME }, // 284
	{ "level", LEVEL }, // 285
	{ "level66", LEVEL66 }, // 286
	{ "level78", LEVEL78 }, // 287
	{ "level88", LEVEL88 }, // 288
	{ "class-name", CLASS_NAME }, // 289
	{ "name", NAME }, // 290
	{ "name88", NAME88 }, // 291
	{ "nume", NUME }, // 292
	{ "numed", NUMED }, // 293
	{ "numed-cr", NUMED_CR }, // 294
	{ "numed-db", NUMED_DB }, // 295
	{ "ninedot", NINEDOT }, // 296
	{ "nines", NINES }, // 297
	{ "ninev", NINEV }, // 298
	{ "pic-p", PIC_P }, // 299
	{ "ones", ONES }, // 300
	{ "spaces", SPACES }, // 301
	{ "space", SPACES }, // 301
	{ "-eq", _EQ }, // 302
	{ "literal", LITERAL }, // 303
	{ "end", END }, // 304
	{ "eop", EOP }, // 305
	{ "-filename", _FILENAME }, // 306
	{ "invalid", INVALID }, // 307
	{ "number", NUMBER }, // 308
	{ "negative", NEGATIVE }, // 309
	{ "numstr", NUMSTR }, // 310
	{ "overflow", OVERFLOW_kw }, // 311
	{ "-binary-integer", _BINARY_INTEGER }, // 312
	{ "computational", COMPUTATIONAL }, // 313
	{ "perform", PERFORM }, // 314
	{ "backward", BACKWARD }, // 315
	{ "positive", POSITIVE }, // 316
	{ "pointer", POINTER }, // 317
	{ "process", PROCESS }, // 318
	{ "section", SECTION }, // 319
	{ "standard-alphabet", STANDARD_ALPHABET }, // 320
	{ "switch", SWITCH }, // 321
	{ "upsi", UPSI }, // 322
	{ "zero", ZERO }, // 323
	{ "zeros", ZERO }, // 323
	{ "zeroes", ZERO }, // 323
	{ "sysin", SYSIN }, // 324
	{ "sysipt", SYSIPT }, // 325
	{ "sysout", SYSOUT }, // 326
	{ "syslist", SYSLIST }, // 327
	{ "syslst", SYSLST }, // 328
	{ "syspunch", SYSPUNCH }, // 329
	{ "syspch", SYSPCH }, // 330
	{ "console", CONSOLE }, // 331
	{ "c01", C01 }, // 332
	{ "c02", C02 }, // 333
	{ "c03", C03 }, // 334
	{ "c04", C04 }, // 335
	{ "c05", C05 }, // 336
	{ "c06", C06 }, // 337
	{ "c07", C07 }, // 338
	{ "c08", C08 }, // 339
	{ "c09", C09 }, // 340
	{ "c10", C10 }, // 341
	{ "c11", C11 }, // 342
	{ "c12", C12 }, // 343
	{ "csp", CSP }, // 344
	{ "s01", S01 }, // 345
	{ "s02", S02 }, // 346
	{ "s03", S03 }, // 347
	{ "s04", S04 }, // 348
	{ "s05", S05 }, // 349
	{ "afp-5a", AFP_5A }, // 350
	{ "stdin", STDIN }, // 351
	{ "stdout", STDOUT }, // 352
	{ "stderr", STDERR }, // 353
	{ "list", LIST }, // 354
	{ "map", MAP }, // 355
	{ "nolist", NOLIST }, // 356
	{ "nomap", NOMAP }, // 357
	{ "nosource", NOSOURCE }, // 358
	{ "might-be", MIGHT_BE }, // 359
	{ "function-udf", FUNCTION_UDF }, // 360
	{ "function-udf-0", FUNCTION_UDF_0 }, // 361
	{ "default", DEFAULT }, // 362
	{ "date-fmt", DATE_FMT }, // 363
	{ "time-fmt", TIME_FMT }, // 364
	{ "datetime-fmt", DATETIME_FMT }, // 365
	{ "flag-02", FLAG_02 }, // 366
	{ "move-to-same-name", MOVE_TO_SAME_NAME }, // 367
	{ "range-exception-for-index", RANGE_EXCEPTION_FOR_INDEX }, // 368
	{ "terminate-with-varying", TERMINATE_WITH_VARYING }, // 369
	{ "flag-14", FLAG_14 }, // 370
	{ "compile-time-arithmetic-expressions", COMPILE_TIME_ARITHMETIC_EXPRESSIONS }, // 371
	{ "i-o-declarative", I_O_DECLARATIVE }, // 372
	{ "i-o-status-04", I_O_STATUS_04 }, // 373
	{ "i-o-status-07", I_O_STATUS_07 }, // 374
	{ "num-ed-zero-figconst", NUM_ED_ZERO_FIGCONST }, // 375
	{ "read-previous", READ_PREVIOUS }, // 376
	{ "ref-mod-zero-length", REF_MOD_ZERO_LENGTH }, // 377
	{ "value-editing", VALUE_EDITING }, // 378
	{ "value-fig-con-length", VALUE_FIG_CON_LENGTH }, // 379
	{ "value-zero", VALUE_ZERO }, // 380
	{ "write-end-of-page", WRITE_END_OF_PAGE }, // 381
	{ "leap-second", LEAP_SECOND }, // 382
	{ "listing", LISTING }, // 383
	{ "propagate", PROPAGATE }, // 384
	{ "zero-length", ZERO_LENGTH }, // 385
	{ "b-and", B_AND }, // 386
	{ "b-not", B_NOT }, // 387
	{ "b-or", B_OR }, // 388
	{ "b-shift-l", B_SHIFT_L }, // 389
	{ "b-shift-lc", B_SHIFT_LC }, // 390
	{ "b-shift-r", B_SHIFT_R }, // 391
	{ "b-shift-rc", B_SHIFT_RC }, // 392
	{ "b-xor", B_XOR }, // 393
	{ "basis", BASIS }, // 394
	{ "cbl", CBL }, // 395
	{ "constant", CONSTANT }, // 396
	{ "copy", COPY }, // 397
	{ "defined", DEFINED }, // 398
	{ "enter", ENTER }, // 399
	{ "feature", FEATURE }, // 400
	{ "insertt", INSERTT }, // 401
	{ "lsub", LSUB }, // 402
	{ "parameter", PARAMETER_kw }, // 403
	{ "override", OVERRIDE }, // 404
	{ "ready", READY }, // 405
	{ "reset", RESET }, // 406
	{ "rsub", RSUB }, // 407
	{ "service-reload", SERVICE_RELOAD }, // 408
	{ "star-cbl", STAR_CBL }, // 409
	{ "subscript", SUBSCRIPT }, // 410
	{ "suppress", SUPPRESS }, // 411
	{ "trace", TRACE }, // 412
	{ "use", USE }, // 413
	{ "cobol-words", COBOL_WORDS }, // 414
	{ "equate", EQUATE }, // 415
	{ "undefine", UNDEFINE }, // 416
	{ "cdf-define", CDF_DEFINE }, // 417
	{ "cdf-display", CDF_DISPLAY }, // 418
	{ "cdf-if", CDF_IF }, // 419
	{ "cdf-else", CDF_ELSE }, // 420
	{ "cdf-end-if", CDF_END_IF }, // 421
	{ "cdf-evaluate", CDF_EVALUATE }, // 422
	{ "cdf-when", CDF_WHEN }, // 423
	{ "cdf-end-evaluate", CDF_END_EVALUATE }, // 424
	{ "call-convention", CALL_CONVENTION }, // 425
	{ "call-cobol", CALL_COBOL }, // 426
	{ "call-verbatim", CALL_VERBATIM }, // 427
	{ "cdf-push", CDF_PUSH }, // 428
	{ "cdf-pop", CDF_POP }, // 429
	{ "source-format", SOURCE_FORMAT }, // 430
	{ "if", IF }, // 431
	{ "then", THEN }, // 432
	{ "else", ELSE }, // 433
	{ "sentence", SENTENCE }, // 434
	{ "accept", ACCEPT }, // 435
	{ "add", ADD }, // 436
	{ "alter", ALTER }, // 437
	{ "call", CALL }, // 438
	{ "cancel", CANCEL }, // 439
	{ "close", CLOSE }, // 440
	{ "compute", COMPUTE }, // 441
	{ "continue", CONTINUE }, // 442
	{ "delete", DELETE }, // 443
	{ "display", DISPLAY }, // 444
	{ "divide", DIVIDE }, // 445
	{ "evaluate", EVALUATE }, // 446
	{ "exit", EXIT }, // 447
	{ "filler", FILLER_kw }, // 448
	{ "goback", GOBACK }, // 449
	{ "goto", GOTO }, // 450
	{ "initialize", INITIALIZE }, // 451
	{ "inspect", INSPECT }, // 452
	{ "merge", MERGE }, // 453
	{ "move", MOVE }, // 454
	{ "multiply", MULTIPLY }, // 455
	{ "open", OPEN }, // 456
	{ "paragraph", PARAGRAPH }, // 457
	{ "read", READ }, // 458
	{ "release", RELEASE }, // 459
	{ "return", RETURN }, // 460
	{ "rewrite", REWRITE }, // 461
	{ "search", SEARCH }, // 462
	{ "set", SET }, // 463
	{ "select", SELECT }, // 464
	{ "sort", SORT }, // 465
	{ "sort-merge", SORT_MERGE }, // 466
	{ "string", STRING_kw }, // 467
	{ "stop", STOP }, // 468
	{ "subtract", SUBTRACT }, // 469
	{ "start", START }, // 470
	{ "unstring", UNSTRING }, // 471
	{ "write", WRITE }, // 472
	{ "when", WHEN }, // 473
	{ "argument-number", ARGUMENT_NUMBER }, // 474
	{ "argument-value", ARGUMENT_VALUE }, // 475
	{ "environment-name", ENVIRONMENT_NAME }, // 476
	{ "environment-value", ENVIRONMENT_VALUE }, // 477
	{ "abs", ABS }, // 478
	{ "access", ACCESS }, // 479
	{ "acos", ACOS }, // 480
	{ "actual", ACTUAL }, // 481
	{ "advancing", ADVANCING }, // 482
	{ "after", AFTER }, // 483
	{ "all", ALL }, // 484
	{ "allocate", ALLOCATE }, // 485
	{ "alphabet", ALPHABET }, // 486
	{ "alphabetic", ALPHABETIC }, // 487
	{ "alphabetic-lower", ALPHABETIC_LOWER }, // 488
	{ "alphabetic-upper", ALPHABETIC_UPPER }, // 489
	{ "alphanumeric", ALPHANUMERIC }, // 490
	{ "alphanumeric-edited", ALPHANUMERIC_EDITED }, // 491
	{ "also", ALSO }, // 492
	{ "alternate", ALTERNATE }, // 493
	{ "annuity", ANNUITY }, // 494
	{ "anum", ANUM }, // 495
	{ "any", ANY }, // 496
	{ "anycase", ANYCASE }, // 497
	{ "apply", APPLY }, // 498
	{ "are", ARE }, // 499
	{ "area", AREA }, // 500
	{ "areas", AREAS }, // 501
	{ "as", AS }, // 502
	{ "ascending", ASCENDING }, // 503
	{ "activating", ACTIVATING }, // 504
	{ "asin", ASIN }, // 505
	{ "assign", ASSIGN }, // 506
	{ "at", AT }, // 507
	{ "atan", ATAN }, // 508
	{ "based", BASED }, // 509
	{ "baseconvert", BASECONVERT }, // 510
	{ "before", BEFORE }, // 511
	{ "binary", BINARY }, // 512
	{ "bit", BIT }, // 513
	{ "bit-of", BIT_OF }, // 514
	{ "bit-to-char", BIT_TO_CHAR }, // 515
	{ "blank", BLANK }, // 516
	{ "block", BLOCK_kw }, // 517
	{ "boolean-of-integer", BOOLEAN_OF_INTEGER }, // 518
	{ "bottom", BOTTOM }, // 519
	{ "by", BY }, // 520
	{ "byte", BYTE }, // 521
	{ "byte-length", BYTE_LENGTH }, // 522
	{ "cf", CF }, // 523
	{ "ch", CH }, // 524
	{ "changed", CHANGED }, // 525
	{ "char", CHAR }, // 526
	{ "char-national", CHAR_NATIONAL }, // 527
	{ "character", CHARACTER }, // 528
	{ "characters", CHARACTERS }, // 529
	{ "checking", CHECKING }, // 530
	{ "class", CLASS }, // 531
	{ "cobol", COBOL }, // 532
	{ "code", CODE }, // 533
	{ "code-set", CODESET }, // 534
	{ "collating", COLLATING }, // 535
	{ "column", COLUMN }, // 536
	{ "combined-datetime", COMBINED_DATETIME }, // 537
	{ "comma", COMMA }, // 538
	{ "command-line", COMMAND_LINE }, // 539
	{ "command-line-count", COMMAND_LINE_COUNT }, // 540
	{ "commit", COMMIT }, // 541
	{ "common", COMMON }, // 542
	{ "concat", CONCAT }, // 543
	{ "condition", CONDITION }, // 544
	{ "configuration", CONFIGURATION }, // 545
	{ "configuration section", CONFIGURATION_SECT }, // 546
	{ "contains", CONTAINS }, // 547
	{ "content", CONTENT }, // 548
	{ "control", CONTROL }, // 549
	{ "controls", CONTROLS }, // 550
	{ "convert", CONVERT }, // 551
	{ "converting", CONVERTING }, // 552
	{ "corresponding", CORRESPONDING }, // 553
	{ "cos", COS }, // 554
	{ "count", COUNT }, // 555
	{ "currency", CURRENCY }, // 556
	{ "current", CURRENT }, // 557
	{ "current-date", CURRENT_DATE }, // 558
	{ "date", DATE }, // 559
	{ "date-compiled", DATE_COMPILED }, // 560
	{ "date-of-integer", DATE_OF_INTEGER }, // 561
	{ "date-to-yyyymmdd", DATE_TO_YYYYMMDD }, // 562
	{ "date-written", DATE_WRITTEN }, // 563
	{ "day", DAY }, // 564
	{ "day-of-integer", DAY_OF_INTEGER }, // 565
	{ "day-of-week", DAY_OF_WEEK }, // 566
	{ "day-to-yyyyddd", DAY_TO_YYYYDDD }, // 567
	{ "dbcs", DBCS }, // 568
	{ "de", DE }, // 569
	{ "debugging", DEBUGGING }, // 570
	{ "decimal-point", DECIMAL_POINT }, // 571
	{ "declaratives", DECLARATIVES }, // 572
	{ "delimited", DELIMITED }, // 573
	{ "delimiter", DELIMITER }, // 574
	{ "depending", DEPENDING }, // 575
	{ "descending", DESCENDING }, // 576
	{ "detail", DETAIL }, // 577
	{ "direct", DIRECT }, // 578
	{ "direct-access", DIRECT_ACCESS }, // 579
	{ "division", DIVISION }, // 580
	{ "down", DOWN }, // 581
	{ "duplicates", DUPLICATES }, // 582
	{ "dynamic", DYNAMIC }, // 583
	{ "e", E }, // 584
	{ "ebcdic", EBCDIC }, // 585
	{ "ec", EC }, // 586
	{ "egcs", EGCS }, // 587
	{ "encoding", ENCODING }, // 588
	{ "entry", ENTRY }, // 589
	{ "every", EVERY }, // 590
	{ "examine", EXAMINE }, // 591
	{ "exhibit", EXHIBIT }, // 592
	{ "exp", EXP }, // 593
	{ "exp10", EXP10 }, // 594
	{ "extend", EXTEND }, // 595
	{ "external", EXTERNAL }, // 596
	{ "exception-file", EXCEPTION_FILE }, // 597
	{ "exception-file-n", EXCEPTION_FILE_N }, // 598
	{ "exception-location", EXCEPTION_LOCATION }, // 599
	{ "exception-location-n", EXCEPTION_LOCATION_N }, // 600
	{ "exception-statement", EXCEPTION_STATEMENT }, // 601
	{ "exception-status", EXCEPTION_STATUS }, // 602
	{ "factorial", FACTORIAL }, // 603
	{ "false", FALSE_kw }, // 604
	{ "fd", FD }, // 605
	{ "file-control", FILE_CONTROL }, // 606
	{ "file", FILE_KW }, // 607
	{ "file-limit", FILE_LIMIT }, // 608
	{ "final", FINAL }, // 609
	{ "finally", FINALLY }, // 610
	{ "find-string", FIND_STRING }, // 611
	{ "first", FIRST }, // 612
	{ "fixed", FIXED }, // 613
	{ "footing", FOOTING }, // 614
	{ "for", FOR }, // 615
	{ "formatted-current-date", FORMATTED_CURRENT_DATE }, // 616
	{ "formatted-date", FORMATTED_DATE }, // 617
	{ "formatted-datetime", FORMATTED_DATETIME }, // 618
	{ "formatted-time", FORMATTED_TIME }, // 619
	{ "form-overflow", FORM_OVERFLOW }, // 620
	{ "free", FREE }, // 621
	{ "fraction-part", FRACTION_PART }, // 622
	{ "from", FROM }, // 623
	{ "function", FUNCTION }, // 624
	{ "generate", GENERATE }, // 625
	{ "giving", GIVING }, // 626
	{ "global", GLOBAL }, // 627
	{ "go", GO }, // 628
	{ "group", GROUP }, // 629
	{ "heading", HEADING }, // 630
	{ "hex", HEX }, // 631
	{ "hex-of", HEX_OF }, // 632
	{ "hex-to-char", HEX_TO_CHAR }, // 633
	{ "high-values", HIGH_VALUES }, // 634
	{ "highest-algebraic", HIGHEST_ALGEBRAIC }, // 635
	{ "hold", HOLD }, // 636
	{ "ibm-360", IBM_360 }, // 637
	{ "in", IN }, // 638
	{ "include", INCLUDE }, // 639
	{ "index", INDEX }, // 640
	{ "indexed", INDEXED }, // 641
	{ "indicate", INDICATE }, // 642
	{ "initial", INITIAL_kw }, // 643
	{ "initiate", INITIATE }, // 644
	{ "input", INPUT }, // 645
	{ "installation", INSTALLATION }, // 646
	{ "interface", INTERFACE }, // 647
	{ "integer", INTEGER }, // 648
	{ "integer-of-boolean", INTEGER_OF_BOOLEAN }, // 649
	{ "integer-of-date", INTEGER_OF_DATE }, // 650
	{ "integer-of-day", INTEGER_OF_DAY }, // 651
	{ "integer-of-formatted-date", INTEGER_OF_FORMATTED_DATE }, // 652
	{ "integer-part", INTEGER_PART }, // 653
	{ "into", INTO }, // 654
	{ "intrinsic", INTRINSIC }, // 655
	{ "invoke", INVOKE }, // 656
	{ "i-o", IO }, // 657
	{ "i-o-control", IO_CONTROL }, // 658
	{ "is", IS }, // 659
	{ "isnt", ISNT }, // 660
	{ "kanji", KANJI }, // 661
	{ "key", KEY }, // 662
	{ "label", LABEL }, // 663
	{ "last", LAST }, // 664
	{ "leading", LEADING }, // 665
	{ "left", LEFT }, // 666
	{ "length", LENGTH }, // 667
	{ "length-of", LENGTH_OF }, // 668
	{ "limit", LIMIT }, // 669
	{ "limits", LIMITS }, // 670
	{ "line", LINE }, // 671
	{ "lines", LINES }, // 672
	{ "line-counter", LINE_COUNTER }, // 673
	{ "linage", LINAGE }, // 674
	{ "linkage", LINKAGE }, // 675
	{ "locale", LOCALE }, // 676
	{ "locale-compare", LOCALE_COMPARE }, // 677
	{ "locale-date", LOCALE_DATE }, // 678
	{ "locale-time", LOCALE_TIME }, // 679
	{ "locale-time-from-seconds", LOCALE_TIME_FROM_SECONDS }, // 680
	{ "local-storage", LOCAL_STORAGE }, // 681
	{ "location", LOCATION }, // 682
	{ "lock", LOCK }, // 683
	{ "lock-on", LOCK_ON }, // 684
	{ "log", LOG }, // 685
	{ "log10", LOG10 }, // 686
	{ "lower-case", LOWER_CASE }, // 687
	{ "low-values", LOW_VALUES }, // 688
	{ "lowest-algebraic", LOWEST_ALGEBRAIC }, // 689
	{ "lparen", LPAREN }, // 690
	{ "manual", MANUAL }, // 691
	{ "maxx", MAXX }, // 692
	{ "mean", MEAN }, // 693
	{ "median", MEDIAN }, // 694
	{ "midrange", MIDRANGE }, // 695
	{ "minn", MINN }, // 696
	{ "multiple", MULTIPLE }, // 697
	{ "mod", MOD }, // 698
	{ "mode", MODE }, // 699
	{ "module-name", MODULE_NAME }, // 700
	{ "named", NAMED }, // 701
	{ "namespace", NAMESPACE }, // 702
	{ "namespace-prefix", NAMESPACE_PREFIX }, // 703
	{ "nat", NAT }, // 704
	{ "national", NATIONAL }, // 705
	{ "national-edited", NATIONAL_EDITED }, // 706
	{ "national-of", NATIONAL_OF }, // 707
	{ "native", NATIVE }, // 708
	{ "nested", NESTED }, // 709
	{ "next", NEXT }, // 710
	{ "no", NO }, // 711
	{ "note", NOTE }, // 712
	{ "nulls", NULLS }, // 713
	{ "null", NULLS }, // 713
	{ "nullptr", NULLPTR }, // 714
	{ "numeric", NUMERIC }, // 715
	{ "numeric-edited", NUMERIC_EDITED }, // 716
	{ "numval", NUMVAL }, // 717
	{ "numval-c", NUMVAL_C }, // 718
	{ "numval-f", NUMVAL_F }, // 719
	{ "occurs", OCCURS }, // 720
	{ "of", OF }, // 721
	{ "off", OFF }, // 722
	{ "omitted", OMITTED }, // 723
	{ "on", ON }, // 724
	{ "only", ONLY }, // 725
	{ "optional", OPTIONAL }, // 726
	{ "options", OPTIONS }, // 727
	{ "ord", ORD }, // 728
	{ "order", ORDER }, // 729
	{ "ord-max", ORD_MAX }, // 730
	{ "ord-min", ORD_MIN }, // 731
	{ "organization", ORGANIZATION }, // 732
	{ "other", OTHER }, // 733
	{ "otherwise", OTHERWISE }, // 734
	{ "output", OUTPUT }, // 735
	{ "packed-decimal", PACKED_DECIMAL }, // 736
	{ "padding", PADDING }, // 737
	{ "page", PAGE }, // 738
	{ "page-counter", PAGE_COUNTER }, // 739
	{ "pf", PF }, // 740
	{ "ph", PH }, // 741
	{ "pi", PI }, // 742
	{ "pic", PIC }, // 743
	{ "picture", PICTURE }, // 744
	{ "plus", PLUS }, // 745
	{ "present-value", PRESENT_VALUE }, // 746
	{ "print-switch", PRINT_SWITCH }, // 747
	{ "procedures", PROCEDURES }, // 748
	{ "proceed", PROCEED }, // 749
	{ "processing", PROCESSING }, // 750
	{ "program-id", PROGRAM_ID }, // 751
	{ "program", PROGRAM_kw }, // 752
	{ "property", PROPERTY }, // 753
	{ "prototype", PROTOTYPE }, // 754
	{ "pseudotext", PSEUDOTEXT }, // 755
	{ "quotes", QUOTES }, // 756
	{ "quote", QUOTES }, // 756
	{ "random", RANDOM }, // 757
	{ "random-seed", RANDOM_SEED }, // 758
	{ "range", RANGE }, // 759
	{ "raise", RAISE }, // 760
	{ "raising", RAISING }, // 761
	{ "rd", RD }, // 762
	{ "record", RECORD }, // 763
	{ "recording", RECORDING }, // 764
	{ "records", RECORDS }, // 765
	{ "recursive", RECURSIVE }, // 766
	{ "redefines", REDEFINES }, // 767
	{ "reel", REEL }, // 768
	{ "reference", REFERENCE }, // 769
	{ "relative", RELATIVE }, // 770
	{ "rem", REM }, // 771
	{ "remainder", REMAINDER }, // 772
	{ "remarks", REMARKS }, // 773
	{ "removal", REMOVAL }, // 774
	{ "renames", RENAMES }, // 775
	{ "replace", REPLACE }, // 776
	{ "replacing", REPLACING }, // 777
	{ "report", REPORT }, // 778
	{ "reporting", REPORTING }, // 779
	{ "reports", REPORTS }, // 780
	{ "repository", REPOSITORY }, // 781
	{ "rerun", RERUN }, // 782
	{ "reserve", RESERVE }, // 783
	{ "restricted", RESTRICTED }, // 784
	{ "resume", RESUME }, // 785
	{ "retry", RETRY }, // 786
	{ "reverse", REVERSE }, // 787
	{ "reversed", REVERSED }, // 788
	{ "rewind", REWIND }, // 789
	{ "rf", RF }, // 790
	{ "rh", RH }, // 791
	{ "right", RIGHT }, // 792
	{ "rounded", ROUNDED }, // 793
	{ "run", RUN }, // 794
	{ "same", SAME }, // 795
	{ "screen", SCREEN }, // 796
	{ "sd", SD }, // 797
	{ "seconds-from-formatted-time", SECONDS_FROM_FORMATTED_TIME }, // 798
	{ "seconds-past-midnight", SECONDS_PAST_MIDNIGHT }, // 799
	{ "security", SECURITY }, // 800
	{ "separate", SEPARATE }, // 801
	{ "sequence", SEQUENCE }, // 802
	{ "sequential", SEQUENTIAL }, // 803
	{ "sharing", SHARING }, // 804
	{ "simple-exit", SIMPLE_EXIT }, // 805
	{ "sign", SIGN }, // 806
	{ "sin", SIN }, // 807
	{ "size", SIZE }, // 808
	{ "smallest-algebraic", SMALLEST_ALGEBRAIC }, // 809
	{ "source", SOURCE }, // 810
	{ "source-computer", SOURCE_COMPUTER }, // 811
	{ "special-names", SPECIAL_NAMES }, // 812
	{ "sqrt", SQRT }, // 813
	{ "stack", STACK }, // 814
	{ "standard", STANDARD }, // 815
	{ "standard-1", STANDARD_1 }, // 816
	{ "standard-2", STANDARD_2 }, // 817
	{ "standard-deviation", STANDARD_DEVIATION }, // 818
	{ "standard-compare", STANDARD_COMPARE }, // 819
	{ "status", STATUS }, // 820
	{ "strong", STRONG }, // 821
	{ "substitute", SUBSTITUTE }, // 822
	{ "sum", SUM }, // 823
	{ "symbol", SYMBOL }, // 824
	{ "symbolic", SYMBOLIC }, // 825
	{ "synchronized", SYNCHRONIZED }, // 826
	{ "tallying", TALLYING }, // 827
	{ "tan", TAN }, // 828
	{ "terminate", TERMINATE }, // 829
	{ "test", TEST }, // 830
	{ "test-date-yyyymmdd", TEST_DATE_YYYYMMDD }, // 831
	{ "test-day-yyyyddd", TEST_DAY_YYYYDDD }, // 832
	{ "test-formatted-datetime", TEST_FORMATTED_DATETIME }, // 833
	{ "test-numval", TEST_NUMVAL }, // 834
	{ "test-numval-c", TEST_NUMVAL_C }, // 835
	{ "test-numval-f", TEST_NUMVAL_F }, // 836
	{ "than", THAN }, // 837
	{ "time", TIME }, // 838
	{ "times", TIMES }, // 839
	{ "to", TO }, // 840
	{ "top", TOP }, // 841
	{ "top-level", TOP_LEVEL }, // 842
	{ "tracks", TRACKS }, // 843
	{ "track-area", TRACK_AREA }, // 844
	{ "trailing", TRAILING }, // 845
	{ "transform", TRANSFORM }, // 846
	{ "trim", TRIM }, // 847
	{ "true", TRUE_kw }, // 848
	{ "try", TRY }, // 849
	{ "turn", TURN }, // 850
	{ "type", TYPE }, // 851
	{ "typedef", TYPEDEF }, // 852
	{ "ulength", ULENGTH }, // 853
	{ "unbounded", UNBOUNDED }, // 854
	{ "unit", UNIT }, // 855
	{ "units", UNITS }, // 856
	{ "unit-record", UNIT_RECORD }, // 857
	{ "until", UNTIL }, // 858
	{ "up", UP }, // 859
	{ "upon", UPON }, // 860
	{ "upos", UPOS }, // 861
	{ "upper-case", UPPER_CASE }, // 862
	{ "usage", USAGE }, // 863
	{ "using", USING }, // 864
	{ "usubstr", USUBSTR }, // 865
	{ "usupplementary", USUPPLEMENTARY }, // 866
	{ "utility", UTILITY }, // 867
	{ "uuid4", UUID4 }, // 868
	{ "uvalid", UVALID }, // 869
	{ "uwidth", UWIDTH }, // 870
	{ "validating", VALIDATING }, // 871
	{ "value", VALUE }, // 872
	{ "variance", VARIANCE }, // 873
	{ "varying", VARYING }, // 874
	{ "volatile", VOLATILE }, // 875
	{ "when-compiled", WHEN_COMPILED }, // 876
	{ "with", WITH }, // 877
	{ "working-storage", WORKING_STORAGE }, // 878
	{ "year-to-yyyy", YEAR_TO_YYYY }, // 879
	{ "yyyyddd", YYYYDDD }, // 880
	{ "yyyymmdd", YYYYMMDD }, // 881
	{ "arithmetic", ARITHMETIC }, // 882
	{ "attribute", ATTRIBUTE }, // 883
	{ "auto", AUTO }, // 884
	{ "automatic", AUTOMATIC }, // 885
	{ "away-from-zero", AWAY_FROM_ZERO }, // 886
	{ "background-color", BACKGROUND_COLOR }, // 887
	{ "bell", BELL }, // 888
	{ "binary-encoding", BINARY_ENCODING }, // 889
	{ "blink", BLINK }, // 890
	{ "capacity", CAPACITY }, // 891
	{ "center", CENTER }, // 892
	{ "classification", CLASSIFICATION }, // 893
	{ "cycle", CYCLE }, // 894
	{ "decimal-encoding", DECIMAL_ENCODING }, // 895
	{ "entry-convention", ENTRY_CONVENTION }, // 896
	{ "eol", EOL }, // 897
	{ "eos", EOS }, // 898
	{ "erase", ERASE }, // 899
	{ "expands", EXPANDS }, // 900
	{ "float-binary", FLOAT_BINARY }, // 901
	{ "float-decimal", FLOAT_DECIMAL }, // 902
	{ "foreground-color", FOREGROUND_COLOR }, // 903
	{ "forever", FOREVER }, // 904
	{ "full", FULL }, // 905
	{ "highlight", HIGHLIGHT }, // 906
	{ "high-order-left", HIGH_ORDER_LEFT }, // 907
	{ "high-order-right", HIGH_ORDER_RIGHT }, // 908
	{ "ignoring", IGNORING }, // 909
	{ "implements", IMPLEMENTS }, // 910
	{ "initialized", INITIALIZED }, // 911
	{ "intermediate", INTERMEDIATE }, // 912
	{ "lc-all", LC_ALL_kw }, // 913
	{ "lc-collate", LC_COLLATE_kw }, // 914
	{ "lc-ctype", LC_CTYPE_kw }, // 915
	{ "lc-messages", LC_MESSAGES_kw }, // 916
	{ "lc-monetary", LC_MONETARY_kw }, // 917
	{ "lc-numeric", LC_NUMERIC_kw }, // 918
	{ "lc-time", LC_TIME_kw }, // 919
	{ "lowlight", LOWLIGHT }, // 920
	{ "nearest-away-from-zero", NEAREST_AWAY_FROM_ZERO }, // 921
	{ "nearest-even", NEAREST_EVEN }, // 922
	{ "nearest-toward-zero", NEAREST_TOWARD_ZERO }, // 923
	{ "none", NONE }, // 924
	{ "normal", NORMAL }, // 925
	{ "numbers", NUMBERS }, // 926
	{ "prefixed", PREFIXED }, // 927
	{ "previous", PREVIOUS }, // 928
	{ "prohibited", PROHIBITED }, // 929
	{ "relation", RELATION }, // 930
	{ "required", REQUIRED }, // 931
	{ "reverse-video", REVERSE_VIDEO }, // 932
	{ "rounding", ROUNDING }, // 933
	{ "seconds", SECONDS }, // 934
	{ "secure", SECURE }, // 935
	{ "short", SHORT }, // 936
	{ "signed", SIGNED_kw }, // 937
	{ "standard-binary", STANDARD_BINARY }, // 938
	{ "standard-decimal", STANDARD_DECIMAL }, // 939
	{ "statement", STATEMENT }, // 940
	{ "step", STEP }, // 941
	{ "structure", STRUCTURE }, // 942
	{ "toward-greater", TOWARD_GREATER }, // 943
	{ "toward-lesser", TOWARD_LESSER }, // 944
	{ "truncation", TRUNCATION }, // 945
	{ "ucs-4", UCS_4 }, // 946
	{ "underline", UNDERLINE }, // 947
	{ "unsigned", UNSIGNED_kw }, // 948
	{ "utf-16", UTF_16 }, // 949
	{ "utf-8", UTF_8 }, // 950
	{ "xml-declaration", XML_DECLARATION }, // 951
	{ "xmlgenerate", XMLGENERATE }, // 952
	{ "xmlparse", XMLPARSE }, // 953
	{ "address", ADDRESS }, // 954
	{ "end-accept", END_ACCEPT }, // 955
	{ "end-add", END_ADD }, // 956
	{ "end-call", END_CALL }, // 957
	{ "end-compute", END_COMPUTE }, // 958
	{ "end-delete", END_DELETE }, // 959
	{ "end-display", END_DISPLAY }, // 960
	{ "end-divide", END_DIVIDE }, // 961
	{ "end-evaluate", END_EVALUATE }, // 962
	{ "end-multiply", END_MULTIPLY }, // 963
	{ "end-perform", END_PERFORM }, // 964
	{ "end-read", END_READ }, // 965
	{ "end-return", END_RETURN }, // 966
	{ "end-rewrite", END_REWRITE }, // 967
	{ "end-search", END_SEARCH }, // 968
	{ "end-start", END_START }, // 969
	{ "end-string", END_STRING }, // 970
	{ "end-subtract", END_SUBTRACT }, // 971
	{ "end-unstring", END_UNSTRING }, // 972
	{ "end-write", END_WRITE }, // 973
	{ "end-xml", END_XML }, // 974
	{ "end-if", END_IF }, // 975
	{ "attributes", ATTRIBUTES }, // 976
	{ "element", ELEMENT }, // 977
	{ "nonnumeric", NONNUMERIC }, // 978
	{ "thru", THRU }, // 979
	{ "through", THRU }, // 979
	{ "or", OR }, // 980
	{ "xor", XOR }, // 981
	{ "and", AND }, // 982
	{ "not", NOT }, // 983
	{ "-ne", _NE }, // 984
	{ "-le", _LE }, // 985
	{ "-ge", _GE }, // 986
	{ "pow", POW }, // 987
	{ "neg", NEG }, // 988
};

// cppcheck-suppress useInitializationList
token_names = {
	"IDENTIFICATION", // 0 (258)
	"IDENTIFICATION", // 1 (259)
	"ENVIRONMENT", // 2 (260)
	"ENVIRONMENT", // 3 (261)
	"DATA", // 4 (262)
	"DATA", // 5 (263)
	"PROCEDURE", // 6 (264)
	"PROCEDURE", // 7 (265)
	"FILE", // 8 (266)
	"INPUT-OUTPUT", // 9 (267)
	"LINKAGE", // 10 (268)
	"LOCAL-STORAGE", // 11 (269)
	"WORKING-STORAGE", // 12 (270)
	"OBJECT-COMPUTER", // 13 (271)
	"DISPLAY-OF", // 14 (272)
	"END-FUNCTION", // 15 (273)
	"END-PROGRAM", // 16 (274)
	"END-SUBPROGRAM", // 17 (275)
	"JUSTIFIED", // 18 (276)
	"RETURNING", // 19 (277)
	"NO-CONDITION", // 20 (278)
	"ALNUM", // 21 (279)
	"ALPHED", // 22 (280)
	"ERROR", // 23 (281)
	"EXCEPTION", // 24 (282)
	"SIZE-ERROR", // 25 (283)
	"EXCEPTION-NAME", // 26 (284)
	"LEVEL", // 27 (285)
	"LEVEL66", // 28 (286)
	"LEVEL78", // 29 (287)
	"LEVEL88", // 30 (288)
	"CLASS-NAME", // 31 (289)
	"NAME", // 32 (290)
	"NAME88", // 33 (291)
	"NUME", // 34 (292)
	"NUMED", // 35 (293)
	"NUMED-CR", // 36 (294)
	"NUMED-DB", // 37 (295)
	"NINEDOT", // 38 (296)
	"NINES", // 39 (297)
	"NINEV", // 40 (298)
	"PIC-P", // 41 (299)
	"ONES", // 42 (300)
	"SPACES", // 43 (301)
	"-EQ", // 44 (302)
	"LITERAL", // 45 (303)
	"END", // 46 (304)
	"EOP", // 47 (305)
	"-FILENAME", // 48 (306)
	"INVALID", // 49 (307)
	"NUMBER", // 50 (308)
	"NEGATIVE", // 51 (309)
	"NUMSTR", // 52 (310)
	"OVERFLOW", // 53 (311)
	"-BINARY-INTEGER", // 54 (312)
	"COMPUTATIONAL", // 55 (313)
	"PERFORM", // 56 (314)
	"BACKWARD", // 57 (315)
	"POSITIVE", // 58 (316)
	"POINTER", // 59 (317)
	"PROCESS", // 60 (318)
	"SECTION", // 61 (319)
	"STANDARD-ALPHABET", // 62 (320)
	"SWITCH", // 63 (321)
	"UPSI", // 64 (322)
	"ZERO", // 65 (323)
	"SYSIN", // 66 (324)
	"SYSIPT", // 67 (325)
	"SYSOUT", // 68 (326)
	"SYSLIST", // 69 (327)
	"SYSLST", // 70 (328)
	"SYSPUNCH", // 71 (329)
	"SYSPCH", // 72 (330)
	"CONSOLE", // 73 (331)
	"C01", // 74 (332)
	"C02", // 75 (333)
	"C03", // 76 (334)
	"C04", // 77 (335)
	"C05", // 78 (336)
	"C06", // 79 (337)
	"C07", // 80 (338)
	"C08", // 81 (339)
	"C09", // 82 (340)
	"C10", // 83 (341)
	"C11", // 84 (342)
	"C12", // 85 (343)
	"CSP", // 86 (344)
	"S01", // 87 (345)
	"S02", // 88 (346)
	"S03", // 89 (347)
	"S04", // 90 (348)
	"S05", // 91 (349)
	"AFP-5A", // 92 (350)
	"STDIN", // 93 (351)
	"STDOUT", // 94 (352)
	"STDERR", // 95 (353)
	"LIST", // 96 (354)
	"MAP", // 97 (355)
	"NOLIST", // 98 (356)
	"NOMAP", // 99 (357)
	"NOSOURCE", // 100 (358)
	"MIGHT-BE", // 101 (359)
	"FUNCTION-UDF", // 102 (360)
	"FUNCTION-UDF-0", // 103 (361)
	"DEFAULT", // 104 (362)
	"DATE-FMT", // 105 (363)
	"TIME-FMT", // 106 (364)
	"DATETIME-FMT", // 107 (365)
	"FLAG-02", // 108 (366)
	"MOVE-TO-SAME-NAME", // 109 (367)
	"RANGE-EXCEPTION-FOR-INDEX", // 110 (368)
	"TERMINATE-WITH-VARYING", // 111 (369)
	"FLAG-14", // 112 (370)
	"COMPILE-TIME-ARITHMETIC-EXPRESSIONS", // 113 (371)
	"I-O-DECLARATIVE", // 114 (372)
	"I-O-STATUS-04", // 115 (373)
	"I-O-STATUS-07", // 116 (374)
	"NUM-ED-ZERO-FIGCONST", // 117 (375)
	"READ-PREVIOUS", // 118 (376)
	"REF-MOD-ZERO-LENGTH", // 119 (377)
	"VALUE-EDITING", // 120 (378)
	"VALUE-FIG-CON-LENGTH", // 121 (379)
	"VALUE-ZERO", // 122 (380)
	"WRITE-END-OF-PAGE", // 123 (381)
	"LEAP-SECOND", // 124 (382)
	"LISTING", // 125 (383)
	"PROPAGATE", // 126 (384)
	"ZERO-LENGTH", // 127 (385)
	"B-AND", // 128 (386)
	"B-NOT", // 129 (387)
	"B-OR", // 130 (388)
	"B-SHIFT-L", // 131 (389)
	"B-SHIFT-LC", // 132 (390)
	"B-SHIFT-R", // 133 (391)
	"B-SHIFT-RC", // 134 (392)
	"B-XOR", // 135 (393)
	"BASIS", // 136 (394)
	"CBL", // 137 (395)
	"CONSTANT", // 138 (396)
	"COPY", // 139 (397)
	"DEFINED", // 140 (398)
	"ENTER", // 141 (399)
	"FEATURE", // 142 (400)
	"INSERTT", // 143 (401)
	"LSUB", // 144 (402)
	"PARAMETER", // 145 (403)
	"OVERRIDE", // 146 (404)
	"READY", // 147 (405)
	"RESET", // 148 (406)
	"RSUB", // 149 (407)
	"SERVICE-RELOAD", // 150 (408)
	"STAR-CBL", // 151 (409)
	"SUBSCRIPT", // 152 (410)
	"SUPPRESS", // 153 (411)
	"TRACE", // 154 (412)
	"USE", // 155 (413)
	"COBOL-WORDS", // 156 (414)
	"EQUATE", // 157 (415)
	"UNDEFINE", // 158 (416)
	"CDF-DEFINE", // 159 (417)
	"CDF-DISPLAY", // 160 (418)
	"CDF-IF", // 161 (419)
	"CDF-ELSE", // 162 (420)
	"CDF-END-IF", // 163 (421)
	"CDF-EVALUATE", // 164 (422)
	"CDF-WHEN", // 165 (423)
	"CDF-END-EVALUATE", // 166 (424)
	"CALL-CONVENTION", // 167 (425)
	"CALL-COBOL", // 168 (426)
	"CALL-VERBATIM", // 169 (427)
	"CDF-PUSH", // 170 (428)
	"CDF-POP", // 171 (429)
	"SOURCE-FORMAT", // 172 (430)
	"IF", // 173 (431)
	"THEN", // 174 (432)
	"ELSE", // 175 (433)
	"SENTENCE", // 176 (434)
	"ACCEPT", // 177 (435)
	"ADD", // 178 (436)
	"ALTER", // 179 (437)
	"CALL", // 180 (438)
	"CANCEL", // 181 (439)
	"CLOSE", // 182 (440)
	"COMPUTE", // 183 (441)
	"CONTINUE", // 184 (442)
	"DELETE", // 185 (443)
	"DISPLAY", // 186 (444)
	"DIVIDE", // 187 (445)
	"EVALUATE", // 188 (446)
	"EXIT", // 189 (447)
	"FILLER", // 190 (448)
	"GOBACK", // 191 (449)
	"GOTO", // 192 (450)
	"INITIALIZE", // 193 (451)
	"INSPECT", // 194 (452)
	"MERGE", // 195 (453)
	"MOVE", // 196 (454)
	"MULTIPLY", // 197 (455)
	"OPEN", // 198 (456)
	"PARAGRAPH", // 199 (457)
	"READ", // 200 (458)
	"RELEASE", // 201 (459)
	"RETURN", // 202 (460)
	"REWRITE", // 203 (461)
	"SEARCH", // 204 (462)
	"SET", // 205 (463)
	"SELECT", // 206 (464)
	"SORT", // 207 (465)
	"SORT-MERGE", // 208 (466)
	"STRING", // 209 (467)
	"STOP", // 210 (468)
	"SUBTRACT", // 211 (469)
	"START", // 212 (470)
	"UNSTRING", // 213 (471)
	"WRITE", // 214 (472)
	"WHEN", // 215 (473)
	"ARGUMENT-NUMBER", // 216 (474)
	"ARGUMENT-VALUE", // 217 (475)
	"ENVIRONMENT-NAME", // 218 (476)
	"ENVIRONMENT-VALUE", // 219 (477)
	"ABS", // 220 (478)
	"ACCESS", // 221 (479)
	"ACOS", // 222 (480)
	"ACTUAL", // 223 (481)
	"ADVANCING", // 224 (482)
	"AFTER", // 225 (483)
	"ALL", // 226 (484)
	"ALLOCATE", // 227 (485)
	"ALPHABET", // 228 (486)
	"ALPHABETIC", // 229 (487)
	"ALPHABETIC-LOWER", // 230 (488)
	"ALPHABETIC-UPPER", // 231 (489)
	"ALPHANUMERIC", // 232 (490)
	"ALPHANUMERIC-EDITED", // 233 (491)
	"ALSO", // 234 (492)
	"ALTERNATE", // 235 (493)
	"ANNUITY", // 236 (494)
	"ANUM", // 237 (495)
	"ANY", // 238 (496)
	"ANYCASE", // 239 (497)
	"APPLY", // 240 (498)
	"ARE", // 241 (499)
	"AREA", // 242 (500)
	"AREAS", // 243 (501)
	"AS", // 244 (502)
	"ASCENDING", // 245 (503)
	"ACTIVATING", // 246 (504)
	"ASIN", // 247 (505)
	"ASSIGN", // 248 (506)
	"AT", // 249 (507)
	"ATAN", // 250 (508)
	"BASED", // 251 (509)
	"BASECONVERT", // 252 (510)
	"BEFORE", // 253 (511)
	"BINARY", // 254 (512)
	"BIT", // 255 (513)
	"BIT-OF", // 256 (514)
	"BIT-TO-CHAR", // 257 (515)
	"BLANK", // 258 (516)
	"BLOCK", // 259 (517)
	"BOOLEAN-OF-INTEGER", // 260 (518)
	"BOTTOM", // 261 (519)
	"BY", // 262 (520)
	"BYTE", // 263 (521)
	"BYTE-LENGTH", // 264 (522)
	"CF", // 265 (523)
	"CH", // 266 (524)
	"CHANGED", // 267 (525)
	"CHAR", // 268 (526)
	"CHAR-NATIONAL", // 269 (527)
	"CHARACTER", // 270 (528)
	"CHARACTERS", // 271 (529)
	"CHECKING", // 272 (530)
	"CLASS", // 273 (531)
	"COBOL", // 274 (532)
	"CODE", // 275 (533)
	"CODE-SET", // 276 (534)
	"COLLATING", // 277 (535)
	"COLUMN", // 278 (536)
	"COMBINED-DATETIME", // 279 (537)
	"COMMA", // 280 (538)
	"COMMAND-LINE", // 281 (539)
	"COMMAND-LINE-COUNT", // 282 (540)
	"COMMIT", // 283 (541)
	"COMMON", // 284 (542)
	"CONCAT", // 285 (543)
	"CONDITION", // 286 (544)
	"CONFIGURATION", // 287 (545)
	"CONFIGURATION", // 288 (546)
	"CONTAINS", // 289 (547)
	"CONTENT", // 290 (548)
	"CONTROL", // 291 (549)
	"CONTROLS", // 292 (550)
	"CONVERT", // 293 (551)
	"CONVERTING", // 294 (552)
	"CORRESPONDING", // 295 (553)
	"COS", // 296 (554)
	"COUNT", // 297 (555)
	"CURRENCY", // 298 (556)
	"CURRENT", // 299 (557)
	"CURRENT-DATE", // 300 (558)
	"DATE", // 301 (559)
	"DATE-COMPILED", // 302 (560)
	"DATE-OF-INTEGER", // 303 (561)
	"DATE-TO-YYYYMMDD", // 304 (562)
	"DATE-WRITTEN", // 305 (563)
	"DAY", // 306 (564)
	"DAY-OF-INTEGER", // 307 (565)
	"DAY-OF-WEEK", // 308 (566)
	"DAY-TO-YYYYDDD", // 309 (567)
	"DBCS", // 310 (568)
	"DE", // 311 (569)
	"DEBUGGING", // 312 (570)
	"DECIMAL-POINT", // 313 (571)
	"DECLARATIVES", // 314 (572)
	"DELIMITED", // 315 (573)
	"DELIMITER", // 316 (574)
	"DEPENDING", // 317 (575)
	"DESCENDING", // 318 (576)
	"DETAIL", // 319 (577)
	"DIRECT", // 320 (578)
	"DIRECT-ACCESS", // 321 (579)
	"DIVISION", // 322 (580)
	"DOWN", // 323 (581)
	"DUPLICATES", // 324 (582)
	"DYNAMIC", // 325 (583)
	"E", // 326 (584)
	"EBCDIC", // 327 (585)
	"EC", // 328 (586)
	"EGCS", // 329 (587)
	"ENCODING", // 330 (588)
	"ENTRY", // 331 (589)
	"EVERY", // 332 (590)
	"EXAMINE", // 333 (591)
	"EXHIBIT", // 334 (592)
	"EXP", // 335 (593)
	"EXP10", // 336 (594)
	"EXTEND", // 337 (595)
	"EXTERNAL", // 338 (596)
	"EXCEPTION-FILE", // 339 (597)
	"EXCEPTION-FILE-N", // 340 (598)
	"EXCEPTION-LOCATION", // 341 (599)
	"EXCEPTION-LOCATION-N", // 342 (600)
	"EXCEPTION-STATEMENT", // 343 (601)
	"EXCEPTION-STATUS", // 344 (602)
	"FACTORIAL", // 345 (603)
	"FALSE", // 346 (604)
	"FD", // 347 (605)
	"FILE-CONTROL", // 348 (606)
	"FILE", // 349 (607)
	"FILE-LIMIT", // 350 (608)
	"FINAL", // 351 (609)
	"FINALLY", // 352 (610)
	"FIND-STRING", // 353 (611)
	"FIRST", // 354 (612)
	"FIXED", // 355 (613)
	"FOOTING", // 356 (614)
	"FOR", // 357 (615)
	"FORMATTED-CURRENT-DATE", // 358 (616)
	"FORMATTED-DATE", // 359 (617)
	"FORMATTED-DATETIME", // 360 (618)
	"FORMATTED-TIME", // 361 (619)
	"FORM-OVERFLOW", // 362 (620)
	"FREE", // 363 (621)
	"FRACTION-PART", // 364 (622)
	"FROM", // 365 (623)
	"FUNCTION", // 366 (624)
	"GENERATE", // 367 (625)
	"GIVING", // 368 (626)
	"GLOBAL", // 369 (627)
	"GO", // 370 (628)
	"GROUP", // 371 (629)
	"HEADING", // 372 (630)
	"HEX", // 373 (631)
	"HEX-OF", // 374 (632)
	"HEX-TO-CHAR", // 375 (633)
	"HIGH-VALUES", // 376 (634)
	"HIGHEST-ALGEBRAIC", // 377 (635)
	"HOLD", // 378 (636)
	"IBM-360", // 379 (637)
	"IN", // 380 (638)
	"INCLUDE", // 381 (639)
	"INDEX", // 382 (640)
	"INDEXED", // 383 (641)
	"INDICATE", // 384 (642)
	"INITIAL", // 385 (643)
	"INITIATE", // 386 (644)
	"INPUT", // 387 (645)
	"INSTALLATION", // 388 (646)
	"INTERFACE", // 389 (647)
	"INTEGER", // 390 (648)
	"INTEGER-OF-BOOLEAN", // 391 (649)
	"INTEGER-OF-DATE", // 392 (650)
	"INTEGER-OF-DAY", // 393 (651)
	"INTEGER-OF-FORMATTED-DATE", // 394 (652)
	"INTEGER-PART", // 395 (653)
	"INTO", // 396 (654)
	"INTRINSIC", // 397 (655)
	"INVOKE", // 398 (656)
	"I-O", // 399 (657)
	"I-O-CONTROL", // 400 (658)
	"IS", // 401 (659)
	"ISNT", // 402 (660)
	"KANJI", // 403 (661)
	"KEY", // 404 (662)
	"LABEL", // 405 (663)
	"LAST", // 406 (664)
	"LEADING", // 407 (665)
	"LEFT", // 408 (666)
	"LENGTH", // 409 (667)
	"LENGTH-OF", // 410 (668)
	"LIMIT", // 411 (669)
	"LIMITS", // 412 (670)
	"LINE", // 413 (671)
	"LINES", // 414 (672)
	"LINE-COUNTER", // 415 (673)
	"LINAGE", // 416 (674)
	"LINKAGE", // 417 (675)
	"LOCALE", // 418 (676)
	"LOCALE-COMPARE", // 419 (677)
	"LOCALE-DATE", // 420 (678)
	"LOCALE-TIME", // 421 (679)
	"LOCALE-TIME-FROM-SECONDS", // 422 (680)
	"LOCAL-STORAGE", // 423 (681)
	"LOCATION", // 424 (682)
	"LOCK", // 425 (683)
	"LOCK-ON", // 426 (684)
	"LOG", // 427 (685)
	"LOG10", // 428 (686)
	"LOWER-CASE", // 429 (687)
	"LOW-VALUES", // 430 (688)
	"LOWEST-ALGEBRAIC", // 431 (689)
	"LPAREN", // 432 (690)
	"MANUAL", // 433 (691)
	"MAXX", // 434 (692)
	"MEAN", // 435 (693)
	"MEDIAN", // 436 (694)
	"MIDRANGE", // 437 (695)
	"MINN", // 438 (696)
	"MULTIPLE", // 439 (697)
	"MOD", // 440 (698)
	"MODE", // 441 (699)
	"MODULE-NAME", // 442 (700)
	"NAMED", // 443 (701)
	"NAMESPACE", // 444 (702)
	"NAMESPACE-PREFIX", // 445 (703)
	"NAT", // 446 (704)
	"NATIONAL", // 447 (705)
	"NATIONAL-EDITED", // 448 (706)
	"NATIONAL-OF", // 449 (707)
	"NATIVE", // 450 (708)
	"NESTED", // 451 (709)
	"NEXT", // 452 (710)
	"NO", // 453 (711)
	"NOTE", // 454 (712)
	"NULLS", // 455 (713)
	"NULLPTR", // 456 (714)
	"NUMERIC", // 457 (715)
	"NUMERIC-EDITED", // 458 (716)
	"NUMVAL", // 459 (717)
	"NUMVAL-C", // 460 (718)
	"NUMVAL-F", // 461 (719)
	"OCCURS", // 462 (720)
	"OF", // 463 (721)
	"OFF", // 464 (722)
	"OMITTED", // 465 (723)
	"ON", // 466 (724)
	"ONLY", // 467 (725)
	"OPTIONAL", // 468 (726)
	"OPTIONS", // 469 (727)
	"ORD", // 470 (728)
	"ORDER", // 471 (729)
	"ORD-MAX", // 472 (730)
	"ORD-MIN", // 473 (731)
	"ORGANIZATION", // 474 (732)
	"OTHER", // 475 (733)
	"OTHERWISE", // 476 (734)
	"OUTPUT", // 477 (735)
	"PACKED-DECIMAL", // 478 (736)
	"PADDING", // 479 (737)
	"PAGE", // 480 (738)
	"PAGE-COUNTER", // 481 (739)
	"PF", // 482 (740)
	"PH", // 483 (741)
	"PI", // 484 (742)
	"PIC", // 485 (743)
	"PICTURE", // 486 (744)
	"PLUS", // 487 (745)
	"PRESENT-VALUE", // 488 (746)
	"PRINT-SWITCH", // 489 (747)
	"PROCEDURES", // 490 (748)
	"PROCEED", // 491 (749)
	"PROCESSING", // 492 (750)
	"PROGRAM-ID", // 493 (751)
	"PROGRAM", // 494 (752)
	"PROPERTY", // 495 (753)
	"PROTOTYPE", // 496 (754)
	"PSEUDOTEXT", // 497 (755)
	"QUOTES", // 498 (756)
	"RANDOM", // 499 (757)
	"RANDOM-SEED", // 500 (758)
	"RANGE", // 501 (759)
	"RAISE", // 502 (760)
	"RAISING", // 503 (761)
	"RD", // 504 (762)
	"RECORD", // 505 (763)
	"RECORDING", // 506 (764)
	"RECORDS", // 507 (765)
	"RECURSIVE", // 508 (766)
	"REDEFINES", // 509 (767)
	"REEL", // 510 (768)
	"REFERENCE", // 511 (769)
	"RELATIVE", // 512 (770)
	"REM", // 513 (771)
	"REMAINDER", // 514 (772)
	"REMARKS", // 515 (773)
	"REMOVAL", // 516 (774)
	"RENAMES", // 517 (775)
	"REPLACE", // 518 (776)
	"REPLACING", // 519 (777)
	"REPORT", // 520 (778)
	"REPORTING", // 521 (779)
	"REPORTS", // 522 (780)
	"REPOSITORY", // 523 (781)
	"RERUN", // 524 (782)
	"RESERVE", // 525 (783)
	"RESTRICTED", // 526 (784)
	"RESUME", // 527 (785)
	"RETRY", // 528 (786)
	"REVERSE", // 529 (787)
	"REVERSED", // 530 (788)
	"REWIND", // 531 (789)
	"RF", // 532 (790)
	"RH", // 533 (791)
	"RIGHT", // 534 (792)
	"ROUNDED", // 535 (793)
	"RUN", // 536 (794)
	"SAME", // 537 (795)
	"SCREEN", // 538 (796)
	"SD", // 539 (797)
	"SECONDS-FROM-FORMATTED-TIME", // 540 (798)
	"SECONDS-PAST-MIDNIGHT", // 541 (799)
	"SECURITY", // 542 (800)
	"SEPARATE", // 543 (801)
	"SEQUENCE", // 544 (802)
	"SEQUENTIAL", // 545 (803)
	"SHARING", // 546 (804)
	"SIMPLE-EXIT", // 547 (805)
	"SIGN", // 548 (806)
	"SIN", // 549 (807)
	"SIZE", // 550 (808)
	"SMALLEST-ALGEBRAIC", // 551 (809)
	"SOURCE", // 552 (810)
	"SOURCE-COMPUTER", // 553 (811)
	"SPECIAL-NAMES", // 554 (812)
	"SQRT", // 555 (813)
	"STACK", // 556 (814)
	"STANDARD", // 557 (815)
	"STANDARD-1", // 558 (816)
	"STANDARD-2", // 559 (817)
	"STANDARD-DEVIATION", // 560 (818)
	"STANDARD-COMPARE", // 561 (819)
	"STATUS", // 562 (820)
	"STRONG", // 563 (821)
	"SUBSTITUTE", // 564 (822)
	"SUM", // 565 (823)
	"SYMBOL", // 566 (824)
	"SYMBOLIC", // 567 (825)
	"SYNCHRONIZED", // 568 (826)
	"TALLYING", // 569 (827)
	"TAN", // 570 (828)
	"TERMINATE", // 571 (829)
	"TEST", // 572 (830)
	"TEST-DATE-YYYYMMDD", // 573 (831)
	"TEST-DAY-YYYYDDD", // 574 (832)
	"TEST-FORMATTED-DATETIME", // 575 (833)
	"TEST-NUMVAL", // 576 (834)
	"TEST-NUMVAL-C", // 577 (835)
	"TEST-NUMVAL-F", // 578 (836)
	"THAN", // 579 (837)
	"TIME", // 580 (838)
	"TIMES", // 581 (839)
	"TO", // 582 (840)
	"TOP", // 583 (841)
	"TOP-LEVEL", // 584 (842)
	"TRACKS", // 585 (843)
	"TRACK-AREA", // 586 (844)
	"TRAILING", // 587 (845)
	"TRANSFORM", // 588 (846)
	"TRIM", // 589 (847)
	"TRUE", // 590 (848)
	"TRY", // 591 (849)
	"TURN", // 592 (850)
	"TYPE", // 593 (851)
	"TYPEDEF", // 594 (852)
	"ULENGTH", // 595 (853)
	"UNBOUNDED", // 596 (854)
	"UNIT", // 597 (855)
	"UNITS", // 598 (856)
	"UNIT-RECORD", // 599 (857)
	"UNTIL", // 600 (858)
	"UP", // 601 (859)
	"UPON", // 602 (860)
	"UPOS", // 603 (861)
	"UPPER-CASE", // 604 (862)
	"USAGE", // 605 (863)
	"USING", // 606 (864)
	"USUBSTR", // 607 (865)
	"USUPPLEMENTARY", // 608 (866)
	"UTILITY", // 609 (867)
	"UUID4", // 610 (868)
	"UVALID", // 611 (869)
	"UWIDTH", // 612 (870)
	"VALIDATING", // 613 (871)
	"VALUE", // 614 (872)
	"VARIANCE", // 615 (873)
	"VARYING", // 616 (874)
	"VOLATILE", // 617 (875)
	"WHEN-COMPILED", // 618 (876)
	"WITH", // 619 (877)
	"WORKING-STORAGE", // 620 (878)
	"YEAR-TO-YYYY", // 621 (879)
	"YYYYDDD", // 622 (880)
	"YYYYMMDD", // 623 (881)
	"ARITHMETIC", // 624 (882)
	"ATTRIBUTE", // 625 (883)
	"AUTO", // 626 (884)
	"AUTOMATIC", // 627 (885)
	"AWAY-FROM-ZERO", // 628 (886)
	"BACKGROUND-COLOR", // 629 (887)
	"BELL", // 630 (888)
	"BINARY-ENCODING", // 631 (889)
	"BLINK", // 632 (890)
	"CAPACITY", // 633 (891)
	"CENTER", // 634 (892)
	"CLASSIFICATION", // 635 (893)
	"CYCLE", // 636 (894)
	"DECIMAL-ENCODING", // 637 (895)
	"ENTRY-CONVENTION", // 638 (896)
	"EOL", // 639 (897)
	"EOS", // 640 (898)
	"ERASE", // 641 (899)
	"EXPANDS", // 642 (900)
	"FLOAT-BINARY", // 643 (901)
	"FLOAT-DECIMAL", // 644 (902)
	"FOREGROUND-COLOR", // 645 (903)
	"FOREVER", // 646 (904)
	"FULL", // 647 (905)
	"HIGHLIGHT", // 648 (906)
	"HIGH-ORDER-LEFT", // 649 (907)
	"HIGH-ORDER-RIGHT", // 650 (908)
	"IGNORING", // 651 (909)
	"IMPLEMENTS", // 652 (910)
	"INITIALIZED", // 653 (911)
	"INTERMEDIATE", // 654 (912)
	"LC-ALL", // 655 (913)
	"LC-COLLATE", // 656 (914)
	"LC-CTYPE", // 657 (915)
	"LC-MESSAGES", // 658 (916)
	"LC-MONETARY", // 659 (917)
	"LC-NUMERIC", // 660 (918)
	"LC-TIME", // 661 (919)
	"LOWLIGHT", // 662 (920)
	"NEAREST-AWAY-FROM-ZERO", // 663 (921)
	"NEAREST-EVEN", // 664 (922)
	"NEAREST-TOWARD-ZERO", // 665 (923)
	"NONE", // 666 (924)
	"NORMAL", // 667 (925)
	"NUMBERS", // 668 (926)
	"PREFIXED", // 669 (927)
	"PREVIOUS", // 670 (928)
	"PROHIBITED", // 671 (929)
	"RELATION", // 672 (930)
	"REQUIRED", // 673 (931)
	"REVERSE-VIDEO", // 674 (932)
	"ROUNDING", // 675 (933)
	"SECONDS", // 676 (934)
	"SECURE", // 677 (935)
	"SHORT", // 678 (936)
	"SIGNED", // 679 (937)
	"STANDARD-BINARY", // 680 (938)
	"STANDARD-DECIMAL", // 681 (939)
	"STATEMENT", // 682 (940)
	"STEP", // 683 (941)
	"STRUCTURE", // 684 (942)
	"TOWARD-GREATER", // 685 (943)
	"TOWARD-LESSER", // 686 (944)
	"TRUNCATION", // 687 (945)
	"UCS-4", // 688 (946)
	"UNDERLINE", // 689 (947)
	"UNSIGNED", // 690 (948)
	"UTF-16", // 691 (949)
	"UTF-8", // 692 (950)
	"XML-DECLARATION", // 693 (951)
	"XMLGENERATE", // 694 (952)
	"XMLPARSE", // 695 (953)
	"ADDRESS", // 696 (954)
	"END-ACCEPT", // 697 (955)
	"END-ADD", // 698 (956)
	"END-CALL", // 699 (957)
	"END-COMPUTE", // 700 (958)
	"END-DELETE", // 701 (959)
	"END-DISPLAY", // 702 (960)
	"END-DIVIDE", // 703 (961)
	"END-EVALUATE", // 704 (962)
	"END-MULTIPLY", // 705 (963)
	"END-PERFORM", // 706 (964)
	"END-READ", // 707 (965)
	"END-RETURN", // 708 (966)
	"END-REWRITE", // 709 (967)
	"END-SEARCH", // 710 (968)
	"END-START", // 711 (969)
	"END-STRING", // 712 (970)
	"END-SUBTRACT", // 713 (971)
	"END-UNSTRING", // 714 (972)
	"END-WRITE", // 715 (973)
	"END-XML", // 716 (974)
	"END-IF", // 717 (975)
	"ATTRIBUTES", // 718 (976)
	"ELEMENT", // 719 (977)
	"NONNUMERIC", // 720 (978)
	"THRU", // 721 (979)
	"OR", // 722 (980)
	"XOR", // 723 (981)
	"AND", // 724 (982)
	"NOT", // 725 (983)
	"-NE", // 726 (984)
	"-LE", // 727 (985)
	"-GE", // 728 (986)
	"POW", // 729 (987)
	"NEG", // 730 (988)
};
