/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __getlocalvartable__
#define __getlocalvartable__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jint JNICALL Java_getlocalvartable_do_1getlocalvartable_1tests (JNIEnv *env, jclass);

#ifdef __cplusplus
}
#endif

#endif /* __getlocalvartable__ */
