
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __org_omg_CORBA_INVALID_TRANSACTION__
#define __org_omg_CORBA_INVALID_TRANSACTION__

#pragma interface

#include <org/omg/CORBA/SystemException.h>
extern "Java"
{
  namespace org
  {
    namespace omg
    {
      namespace CORBA
      {
          class CompletionStatus;
          class INVALID_TRANSACTION;
      }
    }
  }
}

class org::omg::CORBA::INVALID_TRANSACTION : public ::org::omg::CORBA::SystemException
{

public:
  INVALID_TRANSACTION(::java::lang::String *);
  INVALID_TRANSACTION();
  INVALID_TRANSACTION(jint, ::org::omg::CORBA::CompletionStatus *);
  INVALID_TRANSACTION(::java::lang::String *, jint, ::org::omg::CORBA::CompletionStatus *);
private:
  static const jlong serialVersionUID = -4265126403821571697LL;
public:
  static ::java::lang::Class class$;
};

#endif // __org_omg_CORBA_INVALID_TRANSACTION__
