
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_java_beans_encoder_elements_List_Set__
#define __gnu_java_beans_encoder_elements_List_Set__

#pragma interface

#include <gnu/java/beans/encoder/elements/Element.h>
extern "Java"
{
  namespace gnu
  {
    namespace java
    {
      namespace beans
      {
        namespace encoder
        {
            class Writer;
          namespace elements
          {
              class List_Set;
          }
        }
      }
    }
  }
}

class gnu::java::beans::encoder::elements::List_Set : public ::gnu::java::beans::encoder::elements::Element
{

public:
  List_Set();
  virtual void writeStart(::gnu::java::beans::encoder::Writer *);
  static ::java::lang::Class class$;
};

#endif // __gnu_java_beans_encoder_elements_List_Set__
