
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_javax_crypto_sasl_NoSuchMechanismException__
#define __gnu_javax_crypto_sasl_NoSuchMechanismException__

#pragma interface

#include <javax/security/sasl/SaslException.h>
extern "Java"
{
  namespace gnu
  {
    namespace javax
    {
      namespace crypto
      {
        namespace sasl
        {
            class NoSuchMechanismException;
        }
      }
    }
  }
}

class gnu::javax::crypto::sasl::NoSuchMechanismException : public ::javax::security::sasl::SaslException
{

public:
  NoSuchMechanismException(::java::lang::String *);
  static ::java::lang::Class class$;
};

#endif // __gnu_javax_crypto_sasl_NoSuchMechanismException__
