
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_plaf_metal_MetalLookAndFeel$1__
#define __javax_swing_plaf_metal_MetalLookAndFeel$1__

#pragma interface

#include <java/lang/Object.h>
extern "Java"
{
  namespace javax
  {
    namespace swing
    {
        class UIDefaults;
      namespace plaf
      {
        namespace metal
        {
            class MetalLookAndFeel;
            class MetalLookAndFeel$1;
        }
      }
    }
  }
}

class javax::swing::plaf::metal::MetalLookAndFeel$1 : public ::java::lang::Object
{

public: // actually package-private
  MetalLookAndFeel$1(::javax::swing::plaf::metal::MetalLookAndFeel *);
public:
  ::java::lang::Object * createValue(::javax::swing::UIDefaults *);
public: // actually package-private
  ::javax::swing::plaf::metal::MetalLookAndFeel * __attribute__((aligned(__alignof__( ::java::lang::Object)))) this$0;
public:
  static ::java::lang::Class class$;
};

#endif // __javax_swing_plaf_metal_MetalLookAndFeel$1__
