.TH info 1 "7th December 1990"
.SH NAME
info \- GNU's hypertext system
.SH SYNOPSIS
.B info
[
.B \-\-option-name option-value
]
.B \menu-item...
.SH COPYRIGHT
.if n Copyright (C) 1989, 1993 Free Software Foundation, Inc.
.if t Copyright \(co 1989, 1993 Free Software Foundation, Inc.
.SH DESCRIPTION
.LP
The GNU project has a hypertext system called
.I Info
which allows the same source file to be either printed as a
paper manual, or viewed using
.B info.
It is possible to use the
.B info
program from inside Emacs, or to use the stand-alone version described here.
This manual page gives a brief summary of its capabilities.

.SH OPTIONS
.TP
.B \-\-directory directory-path
Add 
.B directory-path 
to the list of directory paths searched when
.B info
needs to find a file.  You may issue 
.B \-\-directory 
multiple times.
Alternatively, you may specify a value for the environment variable
.B INFOPATH;
if 
.B \-\-directory
is not given, the value of 
.B INFOPATH
is used.  The value of 
.B INFOPATH 
is a colon separated list of directory names.  If you do not supply either
.B INFOPATH
or
.B \-\-directory-path,
.B info
uses a default path.
.TP
.B \-f filename
Specify a particular 
.B info
file to visit.  By default,
.B info
visits
the file 
.B dir;
if you use this option, 
.B info
will start with
.B (FILENAME)Top 
as the first file and node.
.TP
.B \-n nodename
Specify a particular node to visit in the initial file that 
.B info
loads.  This is especially useful in conjunction with 
.B \-\-file.
You may specify 
.B \-\-node
multiple times.
.TP
.B -o file
Direct output to
.B file
instead of starting an interactive
.B info
session.
.TP
.B \-h
Produce a relatively brief description of the available 
.B info
options.
.TP
.B \-\-version
Print the version information of 
.B info
and exit.
.TP
.B menu-item
.B info
treats its remaining arguments as the names of menu items.
The first argument is a menu item in the initial node visited,
while the second argument is a menu item in the first argument's
node.  You can easily move to the node of your choice by
specifying the menu names which describe the path to that node.
For example,

.B       info emacs buffers

first selects the menu item 
.B emacs 
in the node 
.B (dir)Top,
and then selects the menu item 
.B buffers
in the node 
.B (emacs)Top.
.SH COMMANDS
When in
.B info
the following commands are available:
.TP
.B h
Invoke the Info tutorial.
.TP
.B ?
Get a short summary of
.B info
commands.
.TP
.B h
Select the
.B info
node from the main directory; this is much more complete than just
using 
.B ?.
.TP
.B Ctrl-g
Abort whatever you are doing.
.TP
.B Ctrl-l
Redraw the screen.
.PP
Selecting other nodes:
.TP
.B n
Move to the "next" node of this node.
.TP
.B p
Move to the "previous" node of this node.
.TP
.B u
Move to this node's "up" node.
.TP
.B m
Pick a menu item specified by name. Picking a menu item causes another
node to be selected. You do not need to type a complete nodename; if
you type a few letters and then a space or tab
.B info
will try to fill in the rest of the nodename. If you ask for further
completion without typing any more characters you'll be given a list
of possibilities; you can also get the list with 
.B ?. 
If you type a few characters and then hit return
.B info
will try to do a completion, and if it is ambigous use the first possibility.
.TP
.B f
Follow a cross reference. You are asked for the name of the reference,
using command completion as for
.B m.
.TP
.B l
Move to the last node you were at.
.PP
Moving within a node:
.TP
.B Space
Scroll forward a page.
.TP
.B DEL
Scroll backward a page.
.TP
.B b
Go to the beginning of this node.
.PP
Advanced commands:
.TP
.B q
Quit 
.B info.
.TP
.B 1
Pick first item in node's menu.
.TP
.B 2 \-\- 5
Pick second ... fifth item in node's menu.
.TP
.B g
Move to node specified by name.	You may include a filename as well,
as 
.B (FILENAME)NODENAME.
.TP
.B s
Search through this 
.B info
file for a specified string, and select the node in which 
the next occurrence is found.
.TP
.B M-x print-node
Pipe the contents of the current node through the command in the
environment variable 
.B INFO_PRINT_COMMAND.
If the variable does not exist, the node is simply piped to 
.B lpr.
.SH ENVIRONMENT
.TP
.B INFOPATH
A colon-separated list of directories to search for 
.B info
files.  Used if 
.B \-\-directory
is not given.
.TP
.B INFO_PRINT_COMMAND
The command used for printing.
.SH SEE ALSO
.BR emacs (1)
.SH AUTHOR
.RS
Brian Fox, Free Software Foundation
.br
bfox@ai.mit.edu
.SH MANUAL AUTHOR
.RS
Robert Lupton; updated by Robert J. Chassell.
.br
rhl@astro.princeton.edu; bob@gnu.ai.mit.edu
