
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_awt_Dialog$ModalityType__
#define __java_awt_Dialog$ModalityType__

#pragma interface

#include <java/lang/Enum.h>
#include <gcj/array.h>

extern "Java"
{
  namespace java
  {
    namespace awt
    {
        class Dialog$ModalityType;
    }
  }
}

class java::awt::Dialog$ModalityType : public ::java::lang::Enum
{

  Dialog$ModalityType(::java::lang::String *, jint);
public:
  static JArray< ::java::awt::Dialog$ModalityType * > * values();
  static ::java::awt::Dialog$ModalityType * valueOf(::java::lang::String *);
  static ::java::awt::Dialog$ModalityType * APPLICATION_MODAL;
  static ::java::awt::Dialog$ModalityType * DOCUMENT_MODAL;
  static ::java::awt::Dialog$ModalityType * MODELESS;
  static ::java::awt::Dialog$ModalityType * TOOLKIT_MODAL;
private:
  static JArray< ::java::awt::Dialog$ModalityType * > * ENUM$VALUES;
public:
  static ::java::lang::Class class$;
};

#endif // __java_awt_Dialog$ModalityType__
