
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_lang_annotation_Annotation__
#define __java_lang_annotation_Annotation__

#pragma interface

#include <java/lang/Object.h>

class java::lang::annotation::Annotation : public ::java::lang::Object
{

public:
  virtual ::java::lang::Class * annotationType() = 0;
  virtual jboolean equals(::java::lang::Object *) = 0;
  virtual jint hashCode() = 0;
  virtual ::java::lang::String * toString() = 0;
  static ::java::lang::Class class$;
} __attribute__ ((java_interface));

#endif // __java_lang_annotation_Annotation__
