@c Copyright (C) 2018-2021 Free Software Foundation, Inc.
@c This is part of the GCC manual.
@c For copying conditions, see the file gcc.texi.


@node lto-dump
@chapter @command{lto-dump}---Tool for dumping LTO object files.

@subsubheading Description

@command{lto-dump} is a tool you can use in conjunction with GCC to
dump link time optimization object files.

@smallexample
Usage: lto-dump @r{[}@var{OPTION}@r{]} ... @var{objfiles}
@end smallexample

@command{lto-dump} accepts the following options:

@subsubheading Synopsis

lto-dump [@option{-list}]
     [@option{-demangle}]
     [@option{-defined-only}]
     [@option{-print-value}]
     [@option{-name-sort}]
     [@option{-size-sort}]
     [@option{-reverse-sort}]
     [@option{-no-sort}]
     [@option{-symbol=}]
     [@option{-objects}]
     [@option{-type-stats}]
     [@option{-tree-stats}]
     [@option{-gimple-stats}]
     [@option{-dump-level=}]
     [@option{-dump-body=}]
     [@option{-help}] @var{lto-dump}

@subsubheading Options

@table @gcctabopt
@item -list
Dumps list of details of functions and variables.

@item -demangle
Dump the demangled output.

@item -defined-only
Dump only the defined symbols.

@item -print-value
Dump initial values of the variables.

@item -name-sort
Sort the symbols alphabetically.

@item -size-sort
Sort the symbols according to size.

@item -reverse-sort
Dump the symbols in reverse order.

@item -no-sort
Dump the symbols in order of occurrence.

@item -symbol=
Dump the details of specific symbol.

@item -objects
Dump the details of LTO objects.

@item -type-stats
Dump the statistics of tree types.

@item -tree-stats
Dump the statistics of trees.

@item -gimple-stats
Dump the statistics of gimple statements.

@item -dump-level=
For deciding the optimization level of body.

@item -dump-body=
Dump the specific gimple body.

@item -help
Display the dump tool help.

@end table
