
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_management_InstanceAlreadyExistsException__
#define __javax_management_InstanceAlreadyExistsException__

#pragma interface

#include <javax/management/OperationsException.h>
extern "Java"
{
  namespace javax
  {
    namespace management
    {
        class InstanceAlreadyExistsException;
    }
  }
}

class javax::management::InstanceAlreadyExistsException : public ::javax::management::OperationsException
{

public:
  InstanceAlreadyExistsException();
  InstanceAlreadyExistsException(::java::lang::String *);
private:
  static const jlong serialVersionUID = 8893743928912733931LL;
public:
  static ::java::lang::Class class$;
};

#endif // __javax_management_InstanceAlreadyExistsException__
