
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_management_InstanceNotFoundException__
#define __javax_management_InstanceNotFoundException__

#pragma interface

#include <javax/management/OperationsException.h>
extern "Java"
{
  namespace javax
  {
    namespace management
    {
        class InstanceNotFoundException;
    }
  }
}

class javax::management::InstanceNotFoundException : public ::javax::management::OperationsException
{

public:
  InstanceNotFoundException();
  InstanceNotFoundException(::java::lang::String *);
private:
  static const jlong serialVersionUID = -882579438394773049LL;
public:
  static ::java::lang::Class class$;
};

#endif // __javax_management_InstanceNotFoundException__
