      INCLUDE "openacc_lib.h"

      IF (ACC_GET_NUM_DEVICES (ACC_DEVICE_HOST) .NE. 1) CALL ABORT
      CALL ACC_SET_DEVICE_TYPE (ACC_DEVICE_HOST)
      IF (ACC_GET_DEVICE_TYPE () .NE. ACC_DEVICE_HOST) CALL ABORT
      CALL ACC_SET_DEVICE_NUM (0, ACC_DEVICE_HOST)
      IF (ACC_GET_DEVICE_NUM (ACC_DEVICE_HOST) .NE. 0) CALL ABORT
      CALL ACC_SHUTDOWN (ACC_DEVICE_HOST)

      CALL ACC_INIT (ACC_DEVICE_HOST)
      CALL ACC_SHUTDOWN (ACC_DEVICE_HOST)

      END
