
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_classpath_jdwp_JdwpConstants$TypeTag__
#define __gnu_classpath_jdwp_JdwpConstants$TypeTag__

#pragma interface

#include <java/lang/Object.h>
extern "Java"
{
  namespace gnu
  {
    namespace classpath
    {
      namespace jdwp
      {
          class JdwpConstants$TypeTag;
      }
    }
  }
}

class gnu::classpath::jdwp::JdwpConstants$TypeTag : public ::java::lang::Object
{

public:
  JdwpConstants$TypeTag();
  static const jbyte CLASS = 1;
  static const jbyte INTERFACE = 2;
  static const jbyte ARRAY = 3;
  static ::java::lang::Class class$;
};

#endif // __gnu_classpath_jdwp_JdwpConstants$TypeTag__
