
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_classpath_jdwp_JdwpConstants$CommandSet$ClassObjectReference__
#define __gnu_classpath_jdwp_JdwpConstants$CommandSet$ClassObjectReference__

#pragma interface

#include <java/lang/Object.h>
extern "Java"
{
  namespace gnu
  {
    namespace classpath
    {
      namespace jdwp
      {
          class JdwpConstants$CommandSet$ClassObjectReference;
      }
    }
  }
}

class gnu::classpath::jdwp::JdwpConstants$CommandSet$ClassObjectReference : public ::java::lang::Object
{

public:
  JdwpConstants$CommandSet$ClassObjectReference();
  static const jbyte CS_VALUE = 17;
  static const jbyte REFLECTED_TYPE = 1;
  static ::java::lang::Class class$;
};

#endif // __gnu_classpath_jdwp_JdwpConstants$CommandSet$ClassObjectReference__
