        .global __prolog_$r13
__prolog_$r13:
        exi     $r13,$sp,0
        jmpi    $r13

        .global __prolog_$r14
__prolog_$r14:
        exi     $r13,$sp,0
        push    $r14
        jmpi    $r13

        .global __prolog_$r15
__prolog_$r15:
        exi     $r13,$sp,0
        push    $r14
        push    $r15
        jmpi    $r13

        .global __prolog_$r16
__prolog_$r16:
        exi     $r13,$sp,0
        push    $r14
        push    $r15
        push    $r16
        jmpi    $r13

        .global __prolog_$r17
__prolog_$r17:
        exi     $r13,$sp,0
        push    $r14
        push    $r15
        push    $r16
        push    $r17
        jmpi    $r13

        .global __prolog_$r18
__prolog_$r18:
        exi     $r13,$sp,0
        push    $r14
        push    $r15
        push    $r16
        push    $r17
        push    $r18
        jmpi    $r13

        .global __prolog_$r19
__prolog_$r19:
        exi     $r13,$sp,0
        push    $r14
        push    $r15
        push    $r16
        push    $r17
        push    $r18
        push    $r19
        jmpi    $r13

        .global __prolog_$r20
__prolog_$r20:
        exi     $r13,$sp,0
        push    $r14
        push    $r15
        push    $r16
        push    $r17
        push    $r18
        push    $r19
        push    $r20
        jmpi    $r13

        .global __prolog_$r21
__prolog_$r21:
        exi     $r13,$sp,0
        push    $r14
        push    $r15
        push    $r16
        push    $r17
        push    $r18
        push    $r19
        push    $r20
        push    $r21
        jmpi    $r13

        .global __prolog_$r22
__prolog_$r22:
        exi     $r13,$sp,0
        push    $r14
        push    $r15
        push    $r16
        push    $r17
        push    $r18
        push    $r19
        push    $r20
        push    $r21
        push    $r22
        jmpi    $r13

        .global __prolog_$r23
__prolog_$r23:
        exi     $r13,$sp,0
        push    $r14
        push    $r15
        push    $r16
        push    $r17
        push    $r18
        push    $r19
        push    $r20
        push    $r21
        push    $r22
        push    $r23
        jmpi    $r13

        .global __prolog_$r24
__prolog_$r24:
        exi     $r13,$sp,0
        push    $r14
        push    $r15
        push    $r16
        push    $r17
        push    $r18
        push    $r19
        push    $r20
        push    $r21
        push    $r22
        push    $r23
        push    $r24
        jmpi    $r13

        .global __prolog_$r25
__prolog_$r25:
        exi     $r13,$sp,0
        push    $r14
        push    $r15
        push    $r16
        push    $r17
        push    $r18
        push    $r19
        push    $r20
        push    $r21
        push    $r22
        push    $r23
        push    $r24
        push    $r25
        jmpi    $r13

        .global __prolog_$r26
__prolog_$r26:
        exi     $r13,$sp,0
        push    $r14
        push    $r15
        push    $r16
        push    $r17
        push    $r18
        push    $r19
        push    $r20
        push    $r21
        push    $r22
        push    $r23
        push    $r24
        push    $r25
        push    $r26
        jmpi    $r13

        .global __prolog_$r27
__prolog_$r27:
        exi     $r13,$sp,0
        push    $r14
        push    $r15
        push    $r16
        push    $r17
        push    $r18
        push    $r19
        push    $r20
        push    $r21
        push    $r22
        push    $r23
        push    $r24
        push    $r25
        push    $r26
        push    $r27
        jmpi    $r13

        .global __prolog_$r28
__prolog_$r28:
        exi     $r13,$sp,0
        push    $r14
        push    $r15
        push    $r16
        push    $r17
        push    $r18
        push    $r19
        push    $r20
        push    $r21
        push    $r22
        push    $r23
        push    $r24
        push    $r25
        push    $r26
        push    $r27
        push    $r28
        jmpi    $r13
