global srcdir subdir

catch { lsort [glob -nocomplain ${srcdir}/${subdir}/*.java] } srcfiles
verbose "srcfiles are $srcfiles"

set prefix ""
foreach x $srcfiles {
    set args [libjava_read_xfail [file rootname $x].xfail]
    if {[file exists [file rootname $x].no-link]} {
	lappend args no-link
    }
    lappend args no-exec

    test_libjava "" "$x" "" "" "" $args
    test_libjava "" "$x" "-O" "" "" $args
}

# Local Variables:
# tcl-indent-level:4
# End:
