# Copyright (C) 2012-2025 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GCC; see the file COPYING3.  If not see
# <http://www.gnu.org/licenses/>.

# Runnable C++ tests for the D2 testsuite.

# Load support procs.
load_lib gdc-dg.exp
load_lib gdc-utils.exp

# If the D runtime library is missing, bail.
if { ![check_effective_target_d_runtime] } {
    return
}

# We are mixing D and C++ code, need to pull in libstdc++
global GDC_INCLUDE_CXX_FLAGS
set GDC_INCLUDE_CXX_FLAGS 1

# Initialize `dg'.
dg-init

# Main loop.
if [check_no_compiler_messages extern_c++_tests assembly {
   // C++
   int main() { return 0; }
}] {
    gdc-do-test [glob -nocomplain $srcdir/$subdir/*.d]
}

set GDC_INCLUDE_CXX_FLAGS 0

# All done.
dg-finish
