.TH go "1" "January 2015" "Go" "User Commands"
.SH NAME
go \- build, test, install Go programs
.SH SYNOPSIS
.B go
\fIcommand\fR [\fIarguments\fR]
.SH DESCRIPTION
.PP
A tool for managing Go source code.  For full documentation run
\fBgo help\fR or see \fBhttp://golang.org/cmd/go\fR.
.SH "SEE ALSO"
.IR gofmt (1)
