
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_javax_crypto_jce_sig_DHKeyFactory__
#define __gnu_javax_crypto_jce_sig_DHKeyFactory__

#pragma interface

#include <java/security/KeyFactorySpi.h>
extern "Java"
{
  namespace gnu
  {
    namespace javax
    {
      namespace crypto
      {
        namespace jce
        {
          namespace sig
          {
              class DHKeyFactory;
          }
        }
      }
    }
  }
  namespace java
  {
    namespace security
    {
        class Key;
        class PrivateKey;
        class PublicKey;
      namespace spec
      {
          class KeySpec;
      }
    }
  }
}

class gnu::javax::crypto::jce::sig::DHKeyFactory : public ::java::security::KeyFactorySpi
{

public:
  DHKeyFactory();
public: // actually protected
  virtual ::java::security::PublicKey * engineGeneratePublic(::java::security::spec::KeySpec *);
  virtual ::java::security::PrivateKey * engineGeneratePrivate(::java::security::spec::KeySpec *);
  virtual ::java::security::spec::KeySpec * engineGetKeySpec(::java::security::Key *, ::java::lang::Class *);
  virtual ::java::security::Key * engineTranslateKey(::java::security::Key *);
public:
  static ::java::lang::Class class$;
};

#endif // __gnu_javax_crypto_jce_sig_DHKeyFactory__
