
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_management_remote_rmi_RMIServer__
#define __javax_management_remote_rmi_RMIServer__

#pragma interface

#include <java/lang/Object.h>
extern "Java"
{
  namespace javax
  {
    namespace management
    {
      namespace remote
      {
        namespace rmi
        {
            class RMIConnection;
            class RMIServer;
        }
      }
    }
  }
}

class javax::management::remote::rmi::RMIServer : public ::java::lang::Object
{

public:
  virtual ::java::lang::String * getVersion() = 0;
  virtual ::javax::management::remote::rmi::RMIConnection * newClient(::java::lang::Object *) = 0;
  static ::java::lang::Class class$;
} __attribute__ ((java_interface));

#endif // __javax_management_remote_rmi_RMIServer__
