
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_xml_stream_EndDocumentImpl__
#define __gnu_xml_stream_EndDocumentImpl__

#pragma interface

#include <gnu/xml/stream/XMLEventImpl.h>
extern "Java"
{
  namespace gnu
  {
    namespace xml
    {
      namespace stream
      {
          class EndDocumentImpl;
      }
    }
  }
  namespace javax
  {
    namespace xml
    {
      namespace stream
      {
          class Location;
      }
    }
  }
}

class gnu::xml::stream::EndDocumentImpl : public ::gnu::xml::stream::XMLEventImpl
{

public: // actually protected
  EndDocumentImpl(::javax::xml::stream::Location *);
public:
  virtual jint getEventType();
  virtual void writeAsEncodedUnicode(::java::io::Writer *);
  static ::java::lang::Class class$;
};

#endif // __gnu_xml_stream_EndDocumentImpl__
