
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_javax_crypto_jce_cipher_PBES2$HMacSHA512$Blowfish__
#define __gnu_javax_crypto_jce_cipher_PBES2$HMacSHA512$Blowfish__

#pragma interface

#include <gnu/javax/crypto/jce/cipher/PBES2$HMacSHA512.h>
extern "Java"
{
  namespace gnu
  {
    namespace javax
    {
      namespace crypto
      {
        namespace jce
        {
          namespace cipher
          {
              class PBES2$HMacSHA512$Blowfish;
          }
        }
      }
    }
  }
}

class gnu::javax::crypto::jce::cipher::PBES2$HMacSHA512$Blowfish : public ::gnu::javax::crypto::jce::cipher::PBES2$HMacSHA512
{

public:
  PBES2$HMacSHA512$Blowfish();
  static ::java::lang::Class class$;
};

#endif // __gnu_javax_crypto_jce_cipher_PBES2$HMacSHA512$Blowfish__
