
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_javax_crypto_jce_cipher_PBES2$HMacTiger$Twofish__
#define __gnu_javax_crypto_jce_cipher_PBES2$HMacTiger$Twofish__

#pragma interface

#include <gnu/javax/crypto/jce/cipher/PBES2$HMacTiger.h>
extern "Java"
{
  namespace gnu
  {
    namespace javax
    {
      namespace crypto
      {
        namespace jce
        {
          namespace cipher
          {
              class PBES2$HMacTiger$Twofish;
          }
        }
      }
    }
  }
}

class gnu::javax::crypto::jce::cipher::PBES2$HMacTiger$Twofish : public ::gnu::javax::crypto::jce::cipher::PBES2$HMacTiger
{

public:
  PBES2$HMacTiger$Twofish();
  static ::java::lang::Class class$;
};

#endif // __gnu_javax_crypto_jce_cipher_PBES2$HMacTiger$Twofish__
