#   Copyright (C) 2001-2025 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with GCC; see the file COPYING3.  If not see
# <http://www.gnu.org/licenses/>.

# This file is based on a bug report submitted to gcc-bugs:
# http://gcc.gnu.org/ml/gcc-patches/2001-12/msg02158.html

# Load support procs.
load_lib gcc-dg.exp

dg-init
if { [istarget "arm*-*-*"] } {
  dg-runtest "$srcdir/$subdir/arm-isr.c" "" ""
}
dg-finish

