#   Copyright (C) 1997 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.  

# Please email any bugs, comments, and/or additions to this file to:
# bug-gcc@prep.ai.mit.edu

# Test the dg.exp driver.
# This is a testsuite tester tester.  As such we *want* to test things like
# expected failure handling.  But expected failures must continually be
# monitored and so in the normal case we create unnecessary work.  So only
# run these tests if DG_TEST is defined to "yes".

global DG_TEST
if { ![info exists DG_TEST] || "$DG_TEST" != "yes" } {
    return
}

# Load support procs.
load_lib gcc-dg.exp

# Initialize harness.
dg-init

# Main loop.
dg-runtest [lsort [glob -nocomplain $srcdir/$subdir/dg-*.c]] "" ""

# All done.
dg-finish
