
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_JScrollBar$ScrollBarChangeListener__
#define __javax_swing_JScrollBar$ScrollBarChangeListener__

#pragma interface

#include <java/lang/Object.h>
extern "Java"
{
  namespace javax
  {
    namespace swing
    {
        class JScrollBar;
        class JScrollBar$ScrollBarChangeListener;
      namespace event
      {
          class ChangeEvent;
      }
    }
  }
}

class javax::swing::JScrollBar$ScrollBarChangeListener : public ::java::lang::Object
{

  JScrollBar$ScrollBarChangeListener(::javax::swing::JScrollBar *);
public:
  virtual void stateChanged(::javax::swing::event::ChangeEvent *);
public: // actually package-private
  JScrollBar$ScrollBarChangeListener(::javax::swing::JScrollBar *, ::javax::swing::JScrollBar$ScrollBarChangeListener *);
  ::javax::swing::JScrollBar * __attribute__((aligned(__alignof__( ::java::lang::Object)))) this$0;
public:
  static ::java::lang::Class class$;
};

#endif // __javax_swing_JScrollBar$ScrollBarChangeListener__
