
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __org_omg_PortableInterceptor_ObjectReferenceTemplateSeqHolder__
#define __org_omg_PortableInterceptor_ObjectReferenceTemplateSeqHolder__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace org
  {
    namespace omg
    {
      namespace CORBA
      {
          class TypeCode;
        namespace portable
        {
            class InputStream;
            class OutputStream;
        }
      }
      namespace PortableInterceptor
      {
          class ObjectReferenceTemplate;
          class ObjectReferenceTemplateSeqHolder;
      }
    }
  }
}

class org::omg::PortableInterceptor::ObjectReferenceTemplateSeqHolder : public ::java::lang::Object
{

public:
  ObjectReferenceTemplateSeqHolder();
  ObjectReferenceTemplateSeqHolder(JArray< ::org::omg::PortableInterceptor::ObjectReferenceTemplate * > *);
  void _read(::org::omg::CORBA::portable::InputStream *);
  void _write(::org::omg::CORBA::portable::OutputStream *);
  ::org::omg::CORBA::TypeCode * _type();
  JArray< ::org::omg::PortableInterceptor::ObjectReferenceTemplate * > * __attribute__((aligned(__alignof__( ::java::lang::Object)))) value;
  static ::java::lang::Class class$;
};

#endif // __org_omg_PortableInterceptor_ObjectReferenceTemplateSeqHolder__
