// Generated from gcc/cobol/words
#ifndef _CDF_H_
#define _CDF_H_
{
	tok_name_t { "CALL-CONVENTION" },
	tok_name_t { "CHECKING" },
	tok_name_t { "COBOL" },
	tok_name_t { "COBOL-WORDS" },
	tok_name_t { "COMPILE-TIME-ARITHMETIC-EXPRESSIONS" },
	tok_name_t { "DE-EDITING" },
	tok_name_t { "DEFINE" },
	tok_name_t { "DEFINED" },
	tok_name_t { "EQUATE" },
	tok_name_t { "EXTERNAL-FILE-FILE-STATUS" },
	tok_name_t { "FIXED" },
	tok_name_t { "FLAG-02" },
	tok_name_t { "FLAG-14" },
	tok_name_t { "FUNCTION-ARGUMENT" },
	tok_name_t { "I-O-DECLARATIVE" },
	tok_name_t { "I-O-STATUS-04" },
	tok_name_t { "I-O-STATUS-07" },
	tok_name_t { "IMP" },
	tok_name_t { "LEAP-SECOND" },
	tok_name_t { "LISTING" },
	tok_name_t { "MOVE-TO-SAME-NAME" },
	tok_name_t { "NUMVAL" },
	tok_name_t { "PARAMETER" },
	tok_name_t { "POP" },
	tok_name_t { "PROPAGATE" },
	tok_name_t { "PUSH" },
	tok_name_t { "READ-PREVIOUS" },
	tok_name_t { "REF-MOD-ZERO-LENGTH" },
	tok_name_t { "SUBSTITUTE" },
	tok_name_t { "TURN" },
	tok_name_t { "UNDEFINE" },
	tok_name_t { "VALUE-EDITING" },
	tok_name_t { "VALUE-FIG-CON-LENGTH" },
	tok_name_t { "VALUE-ZERO" },
	tok_name_t { "WRITE-END-OF-PAGE" },
	tok_name_t { "ZERO-LENGTH" },
}; // end cdf word list
#endif
