SUBROUTINE SCANBUFR (LBUFRIGNOREERROR, LBOPRPRO, LLSPLIT)
LOGICAL :: LBUFRIGNOREERROR, LBOPRPRO, LLSPLIT
INTEGER :: IBOTYP, IBSTYP
IF ((IBOTYP.eq.0).AND.(IBSTYP.eq.1)) GO TO 251
IF ((IBOTYP.eq.0).AND.(IBSTYP.eq.3)) GO TO 251
IF(LBUFRIGNOREERROR) THEN
 goto 360
ENDIF
251  CONTINUE
IF(LBOPRPRO.AND.LLSPLIT) THEN
  CALL OBSCREEN
ENDIF
360 CONTINUE
END SUBROUTINE SCANBUFR

