
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_lang_management_ClassLoadingMXBean__
#define __java_lang_management_ClassLoadingMXBean__

#pragma interface

#include <java/lang/Object.h>

class java::lang::management::ClassLoadingMXBean : public ::java::lang::Object
{

public:
  virtual jint getLoadedClassCount() = 0;
  virtual jlong getTotalLoadedClassCount() = 0;
  virtual jlong getUnloadedClassCount() = 0;
  virtual jboolean isVerbose() = 0;
  virtual void setVerbose(jboolean) = 0;
  static ::java::lang::Class class$;
} __attribute__ ((java_interface));

#endif // __java_lang_management_ClassLoadingMXBean__
