
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_security_cert_CertificateNotYetValidException__
#define __javax_security_cert_CertificateNotYetValidException__

#pragma interface

#include <javax/security/cert/CertificateException.h>
extern "Java"
{
  namespace javax
  {
    namespace security
    {
      namespace cert
      {
          class CertificateNotYetValidException;
      }
    }
  }
}

class javax::security::cert::CertificateNotYetValidException : public ::javax::security::cert::CertificateException
{

public:
  CertificateNotYetValidException();
  CertificateNotYetValidException(::java::lang::String *);
  static ::java::lang::Class class$;
};

#endif // __javax_security_cert_CertificateNotYetValidException__
