[package]
name = "ffi-polonius"
version = "0.1.0"
edition = "2018"
license = "GPL-3"

[lib]
crate-type = ["staticlib"]

[dependencies]
polonius-engine = "0.13.0"

[patch.crates-io]
log = { path = "vendor/log" }
datafrog = { path = "vendor/datafrog" }
polonius-engine = { path = "vendor/polonius-engine" }
rustc-hash = { path = "vendor/rustc-hash" }
