
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_plaf_SliderUI__
#define __javax_swing_plaf_SliderUI__

#pragma interface

#include <javax/swing/plaf/ComponentUI.h>
extern "Java"
{
  namespace javax
  {
    namespace swing
    {
      namespace plaf
      {
          class SliderUI;
      }
    }
  }
}

class javax::swing::plaf::SliderUI : public ::javax::swing::plaf::ComponentUI
{

public:
  SliderUI();
  static ::java::lang::Class class$;
};

#endif // __javax_swing_plaf_SliderUI__
