
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_util_zip_ZipFile$1__
#define __java_util_zip_ZipFile$1__

#pragma interface

#include <java/util/zip/InflaterInputStream.h>

class java::util::zip::ZipFile$1 : public ::java::util::zip::InflaterInputStream
{

public: // actually package-private
  ZipFile$1(::java::util::zip::ZipFile *, ::java::io::InputStream *, ::java::util::zip::Inflater *, jint);
public:
  jint available();
public: // actually package-private
  ::java::util::zip::ZipFile * __attribute__((aligned(__alignof__( ::java::util::zip::InflaterInputStream)))) this$0;
private:
  jint val$sz;
public:
  static ::java::lang::Class class$;
};

#endif // __java_util_zip_ZipFile$1__
