
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_print_attribute_standard_Copies__
#define __javax_print_attribute_standard_Copies__

#pragma interface

#include <javax/print/attribute/IntegerSyntax.h>
extern "Java"
{
  namespace javax
  {
    namespace print
    {
      namespace attribute
      {
        namespace standard
        {
            class Copies;
        }
      }
    }
  }
}

class javax::print::attribute::standard::Copies : public ::javax::print::attribute::IntegerSyntax
{

public:
  Copies(jint);
  jboolean equals(::java::lang::Object *);
  ::java::lang::Class * getCategory();
  ::java::lang::String * getName();
private:
  static const jlong serialVersionUID = -6426631521680023833LL;
public:
  static ::java::lang::Class class$;
};

#endif // __javax_print_attribute_standard_Copies__
