\input texinfo  @c -*-texinfo-*-
@c %**start of header 
@setfilename BUGS
@set BUGSONLY
@c %**end of header

@c The immediately following lines apply to the BUGS file
@c which is generated using this file.
This file lists known bugs in the GNU Fortran compiler.
Copyright (C) 1995, 1996 Free Software Foundation, Inc.
You may copy, distribute, and modify it freely as long as you preserve
this copyright notice and permission notice.

@node Top,,, (dir)
@chapter Bugs in GNU Fortran
@include bugs.texi
@bye
