@setfilename INSTALL
@set INSTALLONLY

@c The immediately following lines apply to the INSTALL file
@c which is generated using this file.
This file contains installation information for the GNU Fortran compiler.
Copyright (C) 1995, 1996 Free Software Foundation, Inc.
You may copy, distribute, and modify it freely as long as you preserve
this copyright notice and permission notice.

@node Top,,, (dir)
@chapter Installing GNU Fortran
@include install.texi
@bye
