
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_xml_xpath_Pattern__
#define __gnu_xml_xpath_Pattern__

#pragma interface

#include <gnu/xml/xpath/Expr.h>
extern "Java"
{
  namespace gnu
  {
    namespace xml
    {
      namespace xpath
      {
          class Pattern;
      }
    }
  }
  namespace org
  {
    namespace w3c
    {
      namespace dom
      {
          class Node;
      }
    }
  }
}

class gnu::xml::xpath::Pattern : public ::gnu::xml::xpath::Expr
{

public:
  Pattern();
  virtual jboolean matches(::org::w3c::dom::Node *) = 0;
  static ::java::lang::Class class$;
};

#endif // __gnu_xml_xpath_Pattern__
