
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_text_GlyphView$GlyphPainter__
#define __javax_swing_text_GlyphView$GlyphPainter__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace java
  {
    namespace awt
    {
        class Graphics;
        class Shape;
    }
  }
  namespace javax
  {
    namespace swing
    {
      namespace text
      {
          class GlyphView;
          class GlyphView$GlyphPainter;
          class Position$Bias;
          class TabExpander;
      }
    }
  }
}

class javax::swing::text::GlyphView$GlyphPainter : public ::java::lang::Object
{

public:
  GlyphView$GlyphPainter();
  virtual jfloat getAscent(::javax::swing::text::GlyphView *) = 0;
  virtual jfloat getDescent(::javax::swing::text::GlyphView *) = 0;
  virtual jfloat getHeight(::javax::swing::text::GlyphView *) = 0;
  virtual jint getBoundedPosition(::javax::swing::text::GlyphView *, jint, jfloat, jfloat) = 0;
  virtual void paint(::javax::swing::text::GlyphView *, ::java::awt::Graphics *, ::java::awt::Shape *, jint, jint) = 0;
  virtual ::java::awt::Shape * modelToView(::javax::swing::text::GlyphView *, jint, ::javax::swing::text::Position$Bias *, ::java::awt::Shape *) = 0;
  virtual jint viewToModel(::javax::swing::text::GlyphView *, jfloat, jfloat, ::java::awt::Shape *, JArray< ::javax::swing::text::Position$Bias * > *) = 0;
  virtual jfloat getSpan(::javax::swing::text::GlyphView *, jint, jint, ::javax::swing::text::TabExpander *, jfloat) = 0;
  virtual jint getNextVisualPositionFrom(::javax::swing::text::GlyphView *, jint, ::javax::swing::text::Position$Bias *, ::java::awt::Shape *, jint, JArray< ::javax::swing::text::Position$Bias * > *);
  virtual ::javax::swing::text::GlyphView$GlyphPainter * getPainter(::javax::swing::text::GlyphView *, jint, jint);
  static ::java::lang::Class class$;
};

#endif // __javax_swing_text_GlyphView$GlyphPainter__
