
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_swing_text_ZoneView$Zone__
#define __javax_swing_text_ZoneView$Zone__

#pragma interface

#include <javax/swing/text/AsyncBoxView.h>
extern "Java"
{
  namespace javax
  {
    namespace swing
    {
      namespace text
      {
          class Element;
          class Position;
          class ZoneView$Zone;
      }
    }
  }
}

class javax::swing::text::ZoneView$Zone : public ::javax::swing::text::AsyncBoxView
{

public: // actually package-private
  ZoneView$Zone(::javax::swing::text::Element *, ::javax::swing::text::Position *, ::javax::swing::text::Position *, jint);
public:
  virtual jint getStartOffset();
  virtual jint getEndOffset();
private:
  ::javax::swing::text::Position * __attribute__((aligned(__alignof__( ::javax::swing::text::AsyncBoxView)))) p0;
  ::javax::swing::text::Position * p1;
public:
  static ::java::lang::Class class$;
};

#endif // __javax_swing_text_ZoneView$Zone__
