# Copyright (C) 2020-2024 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GCC; see the file COPYING3.  If not see
# <http://www.gnu.org/licenses/>.

# Fail compilation tests for the D2 testsuite.

# Load support procs.
load_lib gdc-dg.exp
load_lib gdc-utils.exp

# Initialize `dg'.
dg-init

# Main loop.
gdc-do-test [glob -nocomplain $srcdir/$subdir/*.d]

# All done.
dg-finish
