
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_util_ServiceConfigurationError__
#define __java_util_ServiceConfigurationError__

#pragma interface

#include <java/lang/Error.h>

class java::util::ServiceConfigurationError : public ::java::lang::Error
{

public:
  ServiceConfigurationError(::java::lang::String *);
  ServiceConfigurationError(::java::lang::String *, ::java::lang::Throwable *);
private:
  static const jlong serialVersionUID = 74132770414881LL;
public:
  static ::java::lang::Class class$;
};

#endif // __java_util_ServiceConfigurationError__
