
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_java_util_regex_RETokenNamedProperty$Handler__
#define __gnu_java_util_regex_RETokenNamedProperty$Handler__

#pragma interface

#include <java/lang/Object.h>
extern "Java"
{
  namespace gnu
  {
    namespace java
    {
      namespace util
      {
        namespace regex
        {
            class RETokenNamedProperty$Handler;
        }
      }
    }
  }
}

class gnu::java::util::regex::RETokenNamedProperty$Handler : public ::java::lang::Object
{

  RETokenNamedProperty$Handler();
public:
  virtual jboolean includes(jchar) = 0;
public: // actually package-private
  RETokenNamedProperty$Handler(::gnu::java::util::regex::RETokenNamedProperty$Handler *);
public:
  static ::java::lang::Class class$;
};

#endif // __gnu_java_util_regex_RETokenNamedProperty$Handler__
