name: Remark

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  remark:
    runs-on: ubuntu-latest

    steps:
    # Setup
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Install remark
      run: npm install remark-cli remark-lint remark-lint-maximum-line-length remark-preset-lint-recommended remark-gfm

    # Run
    - name: Check *.md files
      run: git ls-files -z *.md | xargs -0 -n 1 npx remark -u lint -f > /dev/null
