! { dg-do compile }
      SUBROUTINE A9()
!$OMP PARALLEL SECTIONS
!$OMP SECTION
        CALL XAXIS()
!$OMP SECTION
        CALL YAXIS()
!$OMP SECTION
        CALL ZAXIS()
!$OMP END PARALLEL SECTIONS
      END SUBROUTINE A9
