
// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_xml_libxmlj_dom_GnomeDocumentType__
#define __gnu_xml_libxmlj_dom_GnomeDocumentType__

#pragma interface

#include <gnu/xml/libxmlj/dom/GnomeNode.h>
extern "Java"
{
  namespace gnu
  {
    namespace xml
    {
      namespace libxmlj
      {
        namespace dom
        {
            class GnomeDocumentType;
        }
      }
    }
  }
  namespace org
  {
    namespace w3c
    {
      namespace dom
      {
          class NamedNodeMap;
      }
    }
  }
}

class gnu::xml::libxmlj::dom::GnomeDocumentType : public ::gnu::xml::libxmlj::dom::GnomeNode
{

public: // actually package-private
  GnomeDocumentType(::java::lang::Object *);
public:
  virtual ::java::lang::String * getName();
  virtual ::org::w3c::dom::NamedNodeMap * getEntities();
  virtual ::org::w3c::dom::NamedNodeMap * getNotations();
  virtual ::java::lang::String * getPublicId();
  virtual ::java::lang::String * getSystemId();
  virtual ::java::lang::String * getInternalSubset();
  virtual ::java::lang::String * toString();
  static ::java::lang::Class class$;
};

#endif // __gnu_xml_libxmlj_dom_GnomeDocumentType__
